export const DEPARTMENTS = [
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Agri Operations', label: 'Agri Operations' },
  { value: 'Purchase', label: 'Purchase' },
  { value: 'Vendor Sourcing', label: 'Vendor Sourcing' },
  { value: 'HR', label: 'Human Resources' },
  { value: 'MTS', label: 'MTS' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Buy-Back', label: 'Buy-Back' },
  { value: 'Business Development', label: 'Business Development' },
  { value: 'CRM', label: 'CRM' },
  { value: 'Data Analytics & Legal', label: 'Data Analytics & Legal' },
  { value: 'Farmers Factory', label: 'Farmers Factory' },
  { value: 'AgriMart', label: 'AgriMart' },
  { value: 'Palm Cafe', label: 'Palm Cafe' },
  { value: 'Finance', label: 'Finance' },
  { value: 'R&D', label: 'R&D' },
  { value: 'Accounts', label: 'Accounts' },
  { value: 'CEO Office', label: 'CEO Office' },
  { value: 'Admin', label: 'Admin' },
  { value: 'Site Visit', label: 'Site Visit' },
  { value: 'Farm Manager', label: 'Farm Manager' },
  { value: 'Rental Sourcing', label: 'Rental Sourcing' },
  { value: 'TNSkill', label: 'TNSkill' },
  { value: 'Nursery & Landscaping', label: 'Nursery & Landscaping' },
  { value: 'IT & AI', label: 'IT & AI' },
  { value: 'Management Operations Team', label: 'Management Operations Team' },
  { value: 'Valluvam', label: 'Valluvam' },
  { value: 'JV Engineering', label: 'JV Engineering' },
] as const;

export const ROLES = [
  { value: 'CEO', label: 'CEO (Chief Executive Officer)' },
  { value: 'Admin', label: 'Admin' },
  { value: 'HR', label: 'HR (Human Resources)' },
  { value: 'Accounts', label: 'Accounts' },
  { value: 'Employee', label: 'Employee' },
  { value: 'NSM', label: 'NSM (National Senior Manager)' },
  { value: 'DataTeam', label: 'Data Team (Back Office)' },
  { value: 'GM', label: 'GM (General Manager)' },
  { value: 'BOI', label: 'BOI (Back Office Incharge)' },
  { value: 'SMO', label: 'SMO (Senior Manager Operations)' },
  { value: 'GMO', label: 'GMO (General Manager Operations)' },
  { value: 'purchase_head', label: 'Purchase Head' },
  { value: 'vendor_head', label: 'Vendor Head' },
  { value: 'FarmManager', label: 'Farm Manager' },
  { value: 'Auditor', label: 'Auditor' },
  { value: 'Director', label: 'Director' },
  { value: 'BD_Data', label: 'BD Data (Business Development)' },
  { value: 'RSH', label: 'RSH (Rental Sourcing Head)' },
  { value: 'palm_cafe_manager', label: 'Palm Cafe Manager' },
] as const;

export type Department = typeof DEPARTMENTS[number]['value'];
export type Role = typeof ROLES[number]['value'];
