// @ts-nocheck
import React, { useState, useCallback, useEffect } from 'react';
import { format } from 'date-fns';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Plus, Download, Search, Eye, Edit2, X, FileText,
  Building2, Phone, Mail, MapPin, CreditCard, CheckCircle2,
  Clock, AlertCircle, Zap, RefreshCw, Printer, User,
  DollarSign, Calendar, Package, ChevronDown,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { getOpenPOs, markPOBilled, type StoredPO } from '@/lib/purchaseStore';
import { getStoredVendors, vendorDisplayName } from '@/lib/vendorStore';

// ─── Types ────────────────────────────────────────────────────────────────────

type BillStatus = 'draft' | 'pending' | 'approved' | 'paid' | 'overdue';

interface BillLineItem {
  id: number;
  product: string;
  qty: number;
  unit: string;
  rate: number;
  discount: number;
  tax: number;
  amount: number;
}

interface VendorInfo {
  name: string;
  phone: string;
  email: string;
  address: string;
  gstin: string;
  pan: string;
}

interface BankInfo {
  bankName: string;
  accountNumber: string;
  ifscCode: string;
  branch: string;
  accountType: string;
}

interface Bill {
  id: string;
  billNumber: string;
  billDate: string;
  dueDate: string;
  poReference: string;
  vendor: VendorInfo;
  bank: BankInfo;
  lineItems: BillLineItem[];
  notes: string;
  paymentTerms: string;
  status: BillStatus;
  subTotal: number;
  discountAmount: number;
  taxableAmount: number;
  cgst: number;
  sgst: number;
  total: number;
  autoGenerated: boolean;
  createdAt: string;
}

// ─── Local Storage ────────────────────────────────────────────────────────────

const BILL_STORE_KEY = 'ff_erp_bills_v1';

const DEMO_VENDOR: VendorInfo = {
  name: 'Ravi Farms',
  phone: '+91 98765 43210',
  email: 'ravi@ravifarms.com',
  address: '123, Palikarani Main Road, Chennai - 600100',
  gstin: '33AABCR1234F1Z5',
  pan: 'AABCR1234F',
};

const DEMO_BANK: BankInfo = {
  bankName: 'State Bank of India',
  accountNumber: 'XXXX XXXX 4567',
  ifscCode: 'SBIN0001234',
  branch: 'Palikarani Branch',
  accountType: 'Current',
};

const DEMO_BILLS: Bill[] = [
  {
    id: 'bill-demo-1', billNumber: 'BILL-001', billDate: '2026-05-13', dueDate: '2026-05-28',
    poReference: 'PO-00001',
    vendor: { name: 'Ravi Farms', phone: '+91 98765 43210', email: 'ravi@ravifarms.com', address: '123, Palikarani Main Road, Chennai - 600100', gstin: '33AABCR1234F1Z5', pan: 'AABCR1234F' },
    bank: { bankName: 'State Bank of India', accountNumber: 'XXXX XXXX 7890', ifscCode: 'SBIN0001234', branch: 'Palikarani Branch', accountType: 'Current' },
    lineItems: [
      { id: 1, product: 'Onion',  qty: 50, unit: 'kg', rate: 25, discount: 0, tax: 5, amount: 1312.5 },
      { id: 2, product: 'Tomato', qty: 30, unit: 'kg', rate: 40, discount: 0, tax: 5, amount: 1260 },
    ],
    notes: 'Delivered on time. Quality verified by QC team.',
    paymentTerms: 'Net 15', status: 'paid',
    subTotal: 2450, discountAmount: 0, taxableAmount: 2450, cgst: 61.25, sgst: 61.25, total: 2572.5,
    autoGenerated: true, createdAt: '2026-05-13T08:00:00Z',
  },
  {
    id: 'bill-demo-2', billNumber: 'BILL-002', billDate: '2026-05-14', dueDate: '2026-05-29',
    poReference: 'PO-00002',
    vendor: { name: 'AK Traders', phone: '+91 97543 21012', email: 'ak@aktraders.com', address: '78, Koyambedu Market, Chennai - 600107', gstin: '33CCGAK9012H3Z7', pan: 'CCGAK9012H' },
    bank: { bankName: 'Indian Bank', accountNumber: 'XXXX XXXX 2345', ifscCode: 'IDIB000K001', branch: 'Koyambedu Branch', accountType: 'Current' },
    lineItems: [
      { id: 1, product: 'Potato', qty: 40, unit: 'kg', rate: 30, discount: 0, tax: 5, amount: 1260 },
      { id: 2, product: 'Carrot', qty: 20, unit: 'kg', rate: 35, discount: 0, tax: 5, amount: 735 },
    ],
    notes: '',
    paymentTerms: 'Due on Receipt', status: 'pending',
    subTotal: 1900, discountAmount: 0, taxableAmount: 1900, cgst: 47.5, sgst: 47.5, total: 1995,
    autoGenerated: true, createdAt: '2026-05-14T09:30:00Z',
  },
  {
    id: 'bill-demo-3', billNumber: 'BILL-003', billDate: '2026-05-14', dueDate: '2026-06-13',
    poReference: 'PO-00003',
    vendor: { name: 'Fresh Vendors Co.', phone: '+91 98654 32101', email: 'anand@freshvendors.com', address: '45, T Nagar 2nd Street, Chennai - 600017', gstin: '33BBCFV5678G2Z6', pan: 'BBCFV5678G' },
    bank: { bankName: 'HDFC Bank', accountNumber: 'XXXX XXXX 8901', ifscCode: 'HDFC0002345', branch: 'T Nagar Branch', accountType: 'Current' },
    lineItems: [
      { id: 1, product: 'Tomato',    qty: 25, unit: 'kg', rate: 42, discount: 0, tax: 5, amount: 1102.5 },
      { id: 2, product: 'Coriander', qty: 10, unit: 'kg', rate: 60, discount: 0, tax: 5, amount: 630 },
    ],
    notes: 'Net 30 terms agreed.',
    paymentTerms: 'Net 30', status: 'approved',
    subTotal: 1650, discountAmount: 0, taxableAmount: 1650, cgst: 41.25, sgst: 41.25, total: 1732.5,
    autoGenerated: false, createdAt: '2026-05-14T11:00:00Z',
  },
  {
    id: 'bill-demo-4', billNumber: 'BILL-004', billDate: '2026-05-15', dueDate: '2026-05-30',
    poReference: 'PO-00004',
    vendor: { name: 'Green Valley Agro', phone: '+91 96432 10123', email: 'meena@greenvalley.com', address: '89, Velachery Main Road, Chennai - 600042', gstin: '33DDHGV3456I4Z8', pan: 'DDHGV3456I' },
    bank: { bankName: 'Axis Bank', accountNumber: 'XXXX XXXX 3456', ifscCode: 'UTIB0003456', branch: 'Velachery Branch', accountType: 'Savings' },
    lineItems: [
      { id: 1, product: 'Carrot',   qty: 30, unit: 'kg', rate: 35, discount: 0, tax: 5, amount: 1102.5 },
      { id: 2, product: 'Beetroot', qty: 15, unit: 'kg', rate: 28, discount: 0, tax: 5, amount: 441 },
      { id: 3, product: 'Beans',    qty: 20, unit: 'kg', rate: 55, discount: 0, tax: 5, amount: 1155 },
    ],
    notes: 'Root vegetables. Morning delivery confirmed.',
    paymentTerms: 'Net 15', status: 'draft',
    subTotal: 2570, discountAmount: 0, taxableAmount: 2570, cgst: 64.25, sgst: 64.25, total: 2698.5,
    autoGenerated: true, createdAt: '2026-05-15T07:45:00Z',
  },
];

function loadBills(): Bill[] {
  try {
    const raw = localStorage.getItem(BILL_STORE_KEY);
    if (!raw) {
      localStorage.setItem(BILL_STORE_KEY, JSON.stringify(DEMO_BILLS));
      return [...DEMO_BILLS];
    }
    return JSON.parse(raw) as Bill[];
  } catch { return [...DEMO_BILLS]; }
}

function saveBills(bills: Bill[]): void {
  localStorage.setItem(BILL_STORE_KEY, JSON.stringify(bills));
}

function getNextBillSerial(): string {
  const bills = loadBills();
  const max = bills.reduce((m, b) => {
    const n = parseInt(b.billNumber.replace('BILL-', ''), 10) || 0;
    return Math.max(m, n);
  }, 0);
  return `BILL-${String(max + 1).padStart(3, '0')}`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(n: number) { return n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }

function calcBillTotals(items: BillLineItem[]) {
  const subTotal = items.reduce((s, i) => s + i.qty * i.rate, 0);
  const discountAmount = items.reduce((s, i) => s + (i.qty * i.rate * i.discount / 100), 0);
  const taxableAmount = subTotal - discountAmount;
  const totalTax = items.reduce((s, i) => s + (i.qty * i.rate * (1 - i.discount / 100) * i.tax / 100), 0);
  const cgst = totalTax / 2;
  const sgst = totalTax / 2;
  const total = taxableAmount + totalTax;
  return { subTotal, discountAmount, taxableAmount, cgst, sgst, total };
}

// ─── Status Badge ─────────────────────────────────────────────────────────────

function StatusBadge({ status }: { status: BillStatus | string }) {
  const cfg: Record<string, string> = {
    draft: 'bg-gray-100 text-gray-600 border-gray-200',
    pending: 'bg-yellow-100 text-yellow-700 border-yellow-200',
    approved: 'bg-blue-100 text-blue-700 border-blue-200',
    paid: 'bg-green-100 text-green-700 border-green-200',
    overdue: 'bg-red-100 text-red-600 border-red-200',
  };
  const labels: Record<string, string> = {
    draft: 'Draft', pending: 'Pending', approved: 'Approved', paid: 'Paid', overdue: 'Overdue',
  };
  return (
    <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-semibold border ${cfg[status] ?? 'bg-gray-100 text-gray-600 border-gray-200'}`}>
      {labels[status] ?? status}
    </span>
  );
}

// ─── Bill Form (Create / Edit) ────────────────────────────────────────────────

// VENDOR_OPTIONS built dynamically from vendor store inside BillForm

const BANK_OPTIONS: BankInfo[] = [
  { bankName: 'State Bank of India', accountNumber: 'XXXX XXXX 4567', ifscCode: 'SBIN0001234', branch: 'Palikarani Branch', accountType: 'Current' },
  { bankName: 'HDFC Bank', accountNumber: 'XXXX XXXX 8901', ifscCode: 'HDFC0002345', branch: 'T Nagar Branch', accountType: 'Savings' },
  { bankName: 'Indian Bank', accountNumber: 'XXXX XXXX 2345', ifscCode: 'IDIB000A001', branch: 'Tambaram Branch', accountType: 'Current' },
];

function BillForm({
  initialData, onSave, onCancel, fromPO,
}: {
  initialData?: Bill | null;
  onSave: (bill: Bill) => void;
  onCancel: () => void;
  fromPO?: StoredPO | null;
}) {
  const today = format(new Date(), 'yyyy-MM-dd');
  const dueDef = format(new Date(Date.now() + 30 * 86400000), 'yyyy-MM-dd');

  // Build vendor options from vendor store
  const VENDOR_OPTIONS: VendorInfo[] = getStoredVendors().map(v => ({
    name: vendorDisplayName(v),
    phone: v.mobile || v.workPhone || '',
    email: v.email || '',
    address: [v.billing?.street1, v.billing?.city, v.billing?.state, v.billing?.pinCode].filter(Boolean).join(', '),
    gstin: v.gstin || '',
    pan: v.pan || '',
  }));
  // Fallback if store is empty
  if (VENDOR_OPTIONS.length === 0) {
    VENDOR_OPTIONS.push({ name: 'Ravi Farms', phone: '+91 98765 43210', email: 'ravi@ravifarms.com', address: 'Chennai', gstin: '33AABCR1234F1Z5', pan: 'AABCR1234F' });
  }

  const [billNumber] = useState(initialData?.billNumber ?? getNextBillSerial());
  const [billDate, setBillDate] = useState(initialData?.billDate ?? today);
  const [dueDate, setDueDate] = useState(initialData?.dueDate ?? dueDef);
  const [poRef, setPoRef] = useState(initialData?.poReference ?? fromPO?.poNumber ?? '');
  const [selectedVendorIdx, setSelectedVendorIdx] = useState(0);
  const [vendor, setVendor] = useState<VendorInfo>(initialData?.vendor ?? VENDOR_OPTIONS[0]);
  const [bank, setBank] = useState<BankInfo>(initialData?.bank ?? BANK_OPTIONS[0]);
  const [notes, setNotes] = useState(initialData?.notes ?? '');
  const [paymentTerms, setPaymentTerms] = useState(initialData?.paymentTerms ?? 'Net 30');
  const [items, setItems] = useState<BillLineItem[]>(() => {
    if (initialData?.lineItems?.length) return initialData.lineItems;
    if (fromPO?.items?.length) {
      return fromPO.items.map((i, idx) => ({
        id: idx + 1, product: i.itemName, qty: i.quantity, unit: 'kg',
        rate: i.rate, discount: 0, tax: 5,
        amount: i.quantity * i.rate * 1.05,
      }));
    }
    return [{ id: 1, product: '', qty: 0, unit: 'kg', rate: 0, discount: 0, tax: 5, amount: 0 }];
  });

  const openPOs = getOpenPOs();

  const selectVendor = (idx: number) => {
    setSelectedVendorIdx(idx);
    setVendor(VENDOR_OPTIONS[idx]);
    setBank(BANK_OPTIONS[Math.min(idx, BANK_OPTIONS.length - 1)]);
  };

  const updateItem = (id: number, field: keyof BillLineItem, val: any) => {
    setItems(prev => prev.map(item => {
      if (item.id !== id) return item;
      const updated = { ...item, [field]: val };
      const base = updated.qty * updated.rate;
      const disc = base * updated.discount / 100;
      updated.amount = (base - disc) * (1 + updated.tax / 100);
      return updated;
    }));
  };

  const addItem = () => setItems(prev => [...prev, { id: Date.now(), product: '', qty: 0, unit: 'kg', rate: 0, discount: 0, tax: 5, amount: 0 }]);
  const removeItem = (id: number) => { if (items.length > 1) setItems(prev => prev.filter(i => i.id !== id)); };

  const totals = calcBillTotals(items);

  const handleSave = (status: BillStatus) => {
    if (!vendor.name) { toast.error('Select a vendor'); return; }
    if (items.some(i => !i.product.trim())) { toast.error('Fill all product names'); return; }

    const bill: Bill = {
      id: initialData?.id ?? String(Date.now()),
      billNumber,
      billDate, dueDate, poReference: poRef,
      vendor, bank,
      lineItems: items,
      notes, paymentTerms, status,
      ...totals,
      autoGenerated: !!fromPO,
      createdAt: initialData?.createdAt ?? new Date().toISOString(),
    };
    onSave(bill);
  };

  return (
    <div className="space-y-6">
      {/* Header row */}
      <div className="grid grid-cols-3 gap-4">
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1.5">Bill Number</label>
          <input value={billNumber} readOnly className="w-full px-3 py-2 text-sm bg-gray-50 border border-gray-200 rounded-lg text-gray-500 cursor-not-allowed" />
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1.5">Bill Date *</label>
          <input type="date" value={billDate} onChange={e => setBillDate(e.target.value)}
            className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1.5">Due Date</label>
          <input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)}
            className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1.5">Reference PO</label>
          <select value={poRef} onChange={e => setPoRef(e.target.value)}
            className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            <option value="">None</option>
            {openPOs.map(po => <option key={po.id} value={po.poNumber}>{po.poNumber} — {po.vendorName}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1.5">Vendor *</label>
          <select value={selectedVendorIdx} onChange={e => selectVendor(Number(e.target.value))}
            className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            {VENDOR_OPTIONS.map((v, i) => <option key={i} value={i}>{v.name}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs font-semibold text-gray-600 mb-1.5">Payment Terms</label>
          <select value={paymentTerms} onChange={e => setPaymentTerms(e.target.value)}
            className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            {['Due on Receipt', 'Net 15', 'Net 30', 'Net 45', 'Net 60'].map(t => <option key={t}>{t}</option>)}
          </select>
        </div>
      </div>

      {/* Vendor + Bank cards */}
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-3">
            <Building2 size={14} className="text-slate-500" />
            <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wide">Vendor Information</h4>
          </div>
          <div className="space-y-1.5 text-sm">
            <p className="font-bold text-gray-900">{vendor.name}</p>
            <p className="text-gray-600 flex items-center gap-1.5"><Phone size={11} className="text-gray-400" />{vendor.phone}</p>
            <p className="text-gray-600 flex items-center gap-1.5"><Mail size={11} className="text-gray-400" />{vendor.email}</p>
            <p className="text-gray-600 flex items-center gap-1.5"><MapPin size={11} className="text-gray-400" />{vendor.address}</p>
            <div className="flex gap-4 pt-1">
              <p className="text-xs text-gray-500">GSTIN: <span className="font-mono text-gray-700 font-semibold">{vendor.gstin}</span></p>
              <p className="text-xs text-gray-500">PAN: <span className="font-mono text-gray-700 font-semibold">{vendor.pan}</span></p>
            </div>
          </div>
        </div>
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-3">
            <CreditCard size={14} className="text-blue-500" />
            <h4 className="text-xs font-bold text-blue-700 uppercase tracking-wide">Bank Details</h4>
          </div>
          <div className="space-y-1.5 text-sm">
            <p className="font-semibold text-gray-900">{bank.bankName}</p>
            <p className="text-gray-600">A/C: <span className="font-mono font-semibold">{bank.accountNumber}</span></p>
            <p className="text-gray-600">IFSC: <span className="font-mono font-semibold">{bank.ifscCode}</span></p>
            <p className="text-gray-600">Branch: {bank.branch}</p>
            <p className="text-xs text-gray-500 bg-blue-100 rounded px-2 py-0.5 inline-block">{bank.accountType} Account</p>
          </div>
        </div>
      </div>

      {/* Line Items */}
      <div>
        <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wide mb-2">Bill Items</label>
        <div className="border border-gray-200 rounded-xl overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-gray-600 text-xs">
              <tr>
                <th className="px-3 py-2.5 text-left font-semibold">#</th>
                <th className="px-3 py-2.5 text-left font-semibold">Product</th>
                <th className="px-3 py-2.5 text-left font-semibold w-16">Qty</th>
                <th className="px-3 py-2.5 text-left font-semibold w-20">Unit</th>
                <th className="px-3 py-2.5 text-left font-semibold w-24">Rate (₹)</th>
                <th className="px-3 py-2.5 text-left font-semibold w-20">Disc (%)</th>
                <th className="px-3 py-2.5 text-left font-semibold w-20">Tax (%)</th>
                <th className="px-3 py-2.5 text-right font-semibold w-28">Amount (₹)</th>
                <th className="w-8"></th>
              </tr>
            </thead>
            <tbody>
              {items.map((item, idx) => (
                <tr key={item.id} className="border-t border-gray-100">
                  <td className="px-3 py-1.5 text-gray-400 text-xs">{idx + 1}</td>
                  <td className="px-2 py-1.5">
                    <input value={item.product} onChange={e => updateItem(item.id, 'product', e.target.value)}
                      placeholder="Product" className="w-full px-2 py-1 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500" />
                  </td>
                  <td className="px-2 py-1.5">
                    <input type="number" value={item.qty || ''} onChange={e => updateItem(item.id, 'qty', parseFloat(e.target.value) || 0)}
                      className="w-full px-2 py-1 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500" />
                  </td>
                  <td className="px-2 py-1.5">
                    <select value={item.unit} onChange={e => updateItem(item.id, 'unit', e.target.value)}
                      className="w-full px-2 py-1 text-sm border border-gray-200 rounded-lg focus:outline-none">
                      {['kg', 'piece', 'litre', 'dozen', 'box'].map(u => <option key={u}>{u}</option>)}
                    </select>
                  </td>
                  <td className="px-2 py-1.5">
                    <input type="number" value={item.rate || ''} onChange={e => updateItem(item.id, 'rate', parseFloat(e.target.value) || 0)}
                      className="w-full px-2 py-1 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500" />
                  </td>
                  <td className="px-2 py-1.5">
                    <input type="number" value={item.discount || ''} onChange={e => updateItem(item.id, 'discount', parseFloat(e.target.value) || 0)}
                      className="w-full px-2 py-1 text-sm border border-gray-200 rounded-lg focus:outline-none" />
                  </td>
                  <td className="px-2 py-1.5">
                    <select value={item.tax} onChange={e => updateItem(item.id, 'tax', parseFloat(e.target.value))}
                      className="w-full px-2 py-1 text-sm border border-gray-200 rounded-lg focus:outline-none">
                      {[0, 5, 12, 18, 28].map(t => <option key={t} value={t}>{t}%</option>)}
                    </select>
                  </td>
                  <td className="px-3 py-1.5 text-right font-semibold text-gray-900">₹{fmt(item.amount)}</td>
                  <td className="px-1 py-1.5">
                    <button onClick={() => removeItem(item.id)} className="p-1 text-gray-400 hover:text-red-500"><X size={13} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="px-3 py-2 bg-gray-50 border-t border-gray-100">
            <button onClick={addItem} className="flex items-center gap-1.5 text-blue-600 text-sm font-medium hover:text-blue-700">
              <Plus size={14} /> Add Item
            </button>
          </div>
        </div>
      </div>

      {/* Totals */}
      <div className="flex justify-end">
        <div className="w-80 bg-gray-50 border border-gray-200 rounded-xl p-4 space-y-2 text-sm">
          <div className="flex justify-between text-gray-600"><span>Sub Total</span><span>₹{fmt(totals.subTotal)}</span></div>
          <div className="flex justify-between text-gray-600"><span>Discount</span><span className="text-red-600">-₹{fmt(totals.discountAmount)}</span></div>
          <div className="flex justify-between text-gray-600"><span>Taxable Amount</span><span>₹{fmt(totals.taxableAmount)}</span></div>
          <div className="flex justify-between text-gray-600"><span>CGST (2.5%)</span><span>+₹{fmt(totals.cgst)}</span></div>
          <div className="flex justify-between text-gray-600"><span>SGST (2.5%)</span><span>+₹{fmt(totals.sgst)}</span></div>
          <div className="flex justify-between font-bold text-base text-gray-900 border-t border-gray-300 pt-2 mt-1">
            <span>TOTAL AMOUNT</span>
            <span className="text-green-600">₹{fmt(totals.total)}</span>
          </div>
        </div>
      </div>

      {/* Notes */}
      <div>
        <label className="block text-xs font-semibold text-gray-600 mb-1.5">Notes</label>
        <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2}
          placeholder="Payment instructions, terms, or any remarks…"
          className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" />
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-3 pt-2 border-t border-gray-100">
        <button onClick={onCancel} className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 font-medium">Cancel</button>
        <button onClick={() => handleSave('draft')}
          className="px-4 py-2 text-sm border border-gray-300 rounded-xl font-medium text-gray-700 hover:bg-gray-100">
          Save as Draft
        </button>
        <button onClick={() => handleSave('pending')}
          className="px-5 py-2 text-sm bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-semibold">
          Submit Bill
        </button>
      </div>
    </div>
  );
}

// ─── View Bill Modal ──────────────────────────────────────────────────────────

function ViewBillModal({ bill, onClose, onDownload }: { bill: Bill; onClose: () => void; onDownload: (bill: Bill) => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b bg-gradient-to-r from-slate-800 to-slate-900 rounded-t-2xl">
          <div>
            <h2 className="text-xl font-bold text-white">{bill.billNumber}</h2>
            <p className="text-slate-300 text-sm mt-0.5">{bill.vendor.name} · {bill.billDate}</p>
          </div>
          <div className="flex items-center gap-3">
            <StatusBadge status={bill.status} />
            <button onClick={() => onDownload(bill)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-white/10 hover:bg-white/20 text-white text-xs font-medium rounded-lg">
              <Download size={13} /> PDF
            </button>
            <button onClick={onClose} className="p-2 text-slate-300 hover:text-white"><X size={20} /></button>
          </div>
        </div>

        <div className="p-6 space-y-5">
          {/* Vendor + Bank */}
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-gray-50 rounded-xl p-4">
              <p className="text-xs font-bold text-gray-500 uppercase tracking-wide mb-2">Vendor</p>
              <p className="font-bold text-gray-900">{bill.vendor.name}</p>
              <p className="text-sm text-gray-600 mt-1">{bill.vendor.phone}</p>
              <p className="text-sm text-gray-600">{bill.vendor.email}</p>
              <p className="text-sm text-gray-600">{bill.vendor.address}</p>
              <p className="text-xs text-gray-500 mt-1">GSTIN: {bill.vendor.gstin}</p>
            </div>
            <div className="bg-blue-50 rounded-xl p-4">
              <p className="text-xs font-bold text-blue-600 uppercase tracking-wide mb-2">Bank Details</p>
              <p className="font-semibold text-gray-900">{bill.bank.bankName}</p>
              <p className="text-sm text-gray-600 mt-1">A/C: {bill.bank.accountNumber}</p>
              <p className="text-sm text-gray-600">IFSC: {bill.bank.ifscCode}</p>
              <p className="text-sm text-gray-600">{bill.bank.branch}</p>
            </div>
          </div>

          {/* Bill info */}
          <div className="grid grid-cols-3 gap-4 text-sm bg-gray-50 rounded-xl p-4">
            <div><span className="text-gray-500 text-xs">Bill Date</span><p className="font-semibold text-gray-900 mt-0.5">{bill.billDate}</p></div>
            <div><span className="text-gray-500 text-xs">Due Date</span><p className="font-semibold text-gray-900 mt-0.5">{bill.dueDate || '—'}</p></div>
            <div><span className="text-gray-500 text-xs">PO Ref</span><p className="font-semibold font-mono text-gray-900 mt-0.5">{bill.poReference || '—'}</p></div>
          </div>

          {/* Line Items */}
          <div className="border border-gray-200 rounded-xl overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 text-gray-600 text-xs">
                <tr>
                  <th className="px-4 py-2.5 text-left font-semibold">#</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Product</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Qty</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Unit</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Rate (₹)</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Tax (%)</th>
                  <th className="px-4 py-2.5 text-right font-semibold">Amount (₹)</th>
                </tr>
              </thead>
              <tbody>
                {bill.lineItems.map((item, idx) => (
                  <tr key={idx} className="border-t border-gray-100">
                    <td className="px-4 py-2.5 text-gray-400">{idx + 1}</td>
                    <td className="px-4 py-2.5 font-medium text-gray-800">{item.product}</td>
                    <td className="px-4 py-2.5 text-gray-700">{item.qty}</td>
                    <td className="px-4 py-2.5 text-gray-500">{item.unit}</td>
                    <td className="px-4 py-2.5 text-gray-700">₹{fmt(item.rate)}</td>
                    <td className="px-4 py-2.5 text-gray-500">{item.tax}%</td>
                    <td className="px-4 py-2.5 text-right font-semibold text-gray-900">₹{fmt(item.amount)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Totals */}
          <div className="flex justify-end">
            <div className="w-72 space-y-2 text-sm">
              <div className="flex justify-between text-gray-600"><span>Sub Total</span><span>₹{fmt(bill.subTotal)}</span></div>
              <div className="flex justify-between text-gray-600"><span>Discount</span><span className="text-red-500">-₹{fmt(bill.discountAmount)}</span></div>
              <div className="flex justify-between text-gray-600"><span>CGST (2.5%)</span><span>+₹{fmt(bill.cgst)}</span></div>
              <div className="flex justify-between text-gray-600"><span>SGST (2.5%)</span><span>+₹{fmt(bill.sgst)}</span></div>
              <div className="flex justify-between font-bold text-base text-gray-900 border-t pt-2">
                <span>TOTAL</span>
                <span className="text-green-600">₹{fmt(bill.total)}</span>
              </div>
            </div>
          </div>

          {bill.notes && (
            <div className="bg-amber-50 border border-amber-100 rounded-xl p-3 text-sm text-gray-700">{bill.notes}</div>
          )}
        </div>

        <div className="flex justify-end gap-3 p-4 border-t bg-gray-50 rounded-b-2xl">
          <button onClick={() => onDownload(bill)}
            className="flex items-center gap-1.5 px-4 py-2 text-sm border border-gray-300 rounded-xl font-medium text-gray-700 hover:bg-gray-100">
            <Download size={14} /> Download PDF
          </button>
          <button onClick={onClose} className="px-5 py-2 text-sm bg-gray-800 text-white rounded-xl font-medium hover:bg-gray-900">Close</button>
        </div>
      </div>
    </div>
  );
}

// ─── PDF Generator ────────────────────────────────────────────────────────────

function generateBillPDF(bill: Bill) {
  const doc = new jsPDF() as any;

  // Title
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PURCHASE BILL', 105, 16, { align: 'center' });
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Farmers Factory — FF Operations', 105, 25, { align: 'center' });

  doc.setTextColor(30, 41, 59);

  // Bill info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Bill No: ${bill.billNumber}`, 14, 45);
  doc.text(`Date: ${bill.billDate}`, 140, 45);
  doc.setFont('helvetica', 'normal');
  doc.text(`Due Date: ${bill.dueDate || '—'}`, 140, 52);
  if (bill.poReference) doc.text(`PO Ref: ${bill.poReference}`, 140, 59);

  // Vendor
  doc.setFont('helvetica', 'bold');
  doc.text('Vendor:', 14, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(bill.vendor.name, 14, 62);
  doc.text(bill.vendor.phone, 14, 68);
  doc.text(bill.vendor.address, 14, 74);
  doc.text(`GSTIN: ${bill.vendor.gstin}`, 14, 80);

  // Bank
  doc.setFont('helvetica', 'bold');
  doc.text('Bank Details:', 14, 92);
  doc.setFont('helvetica', 'normal');
  doc.text(`${bill.bank.bankName}`, 14, 99);
  doc.text(`A/C: ${bill.bank.accountNumber}`, 14, 105);
  doc.text(`IFSC: ${bill.bank.ifscCode}`, 14, 111);
  doc.text(`Branch: ${bill.bank.branch}`, 14, 117);

  // Items table
  autoTable(doc, {
    startY: 127,
    head: [['Product', 'Qty', 'Unit', 'Rate (₹)', 'Disc%', 'Tax%', 'Amount (₹)']],
    body: bill.lineItems.map(i => [
      i.product, i.qty, i.unit,
      `₹${i.rate.toLocaleString('en-IN')}`,
      `${i.discount}%`, `${i.tax}%`,
      `₹${i.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
    ]),
    headStyles: { fillColor: [30, 41, 59], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    foot: [['', '', '', '', '', 'SUB TOTAL', `₹${bill.subTotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`]],
    footStyles: { fillColor: [243, 244, 246], textColor: [30, 41, 59], fontStyle: 'bold', fontSize: 9 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 8;

  // Totals
  const totalsData = [
    ['CGST (2.5%)', `+₹${bill.cgst.toFixed(2)}`],
    ['SGST (2.5%)', `+₹${bill.sgst.toFixed(2)}`],
    ['TOTAL AMOUNT', `₹${bill.total.toFixed(2)}`],
  ];

  let y = finalY;
  doc.setFontSize(10);
  totalsData.forEach(([label, value], idx) => {
    const isFinal = idx === totalsData.length - 1;
    if (isFinal) {
      doc.setFillColor(34, 197, 94);
      doc.rect(120, y - 5, 76, 10, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setTextColor(80, 80, 80);
      doc.setFont('helvetica', 'normal');
    }
    doc.text(label, 125, y);
    doc.text(value, 192, y, { align: 'right' });
    y += 10;
  });

  if (bill.notes) {
    doc.setTextColor(80, 80, 80);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.text(`Notes: ${bill.notes}`, 14, y + 5);
  }

  doc.save(`${bill.billNumber}.pdf`);
  toast.success(`📄 ${bill.billNumber}.pdf downloaded`);
}

// ─── Auto Bill from PO Modal ──────────────────────────────────────────────────

function AutoBillFromPOModal({ onClose, onCreated }: { onClose: () => void; onCreated: (bill: Bill) => void }) {
  const openPOs = getOpenPOs();
  const [selectedPO, setSelectedPO] = useState<StoredPO | null>(null);

  const handleSelect = (po: StoredPO) => {
    setSelectedPO(po);
  };

  if (selectedPO) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
          <div className="flex items-center justify-between p-6 border-b sticky top-0 bg-white z-10">
            <div>
              <h2 className="text-xl font-bold text-gray-900">Auto Bill from {selectedPO.poNumber}</h2>
              <p className="text-sm text-gray-500 mt-0.5">Pre-filled from PO data · Review and submit</p>
            </div>
            <button onClick={onClose} className="p-2 rounded-lg hover:bg-gray-100"><X size={20} /></button>
          </div>
          <div className="p-6">
            <BillForm
              fromPO={selectedPO}
              onSave={(bill) => {
                markPOBilled(selectedPO.poNumber);
                onCreated(bill);
                onClose();
              }}
              onCancel={() => setSelectedPO(null)}
            />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg">
        <div className="flex items-center justify-between p-6 border-b">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Auto Bill from PO</h2>
            <p className="text-sm text-gray-500 mt-0.5">Select an open Purchase Order</p>
          </div>
          <button onClick={onClose} className="p-2 rounded-lg hover:bg-gray-100"><X size={20} /></button>
        </div>
        <div className="p-4 space-y-2 max-h-80 overflow-y-auto">
          {openPOs.length === 0 && (
            <p className="text-center text-gray-400 py-8 text-sm">No open POs available. Create a PO first.</p>
          )}
          {openPOs.map(po => (
            <button key={po.id} onClick={() => handleSelect(po)}
              className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-blue-50 hover:border-blue-200 border border-gray-200 rounded-xl transition-all text-left">
              <div>
                <p className="font-bold text-blue-600 font-mono">{po.poNumber}</p>
                <p className="text-sm text-gray-700 mt-0.5">{po.vendorName}</p>
                <p className="text-xs text-gray-400">{po.items.map(i => i.itemName).join(', ')}</p>
              </div>
              <div className="text-right">
                <p className="font-bold text-gray-900">₹{po.total.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</p>
                <p className="text-xs text-gray-500">{po.date}</p>
              </div>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function AutoBillPage() {
  const [bills, setBills] = useState<Bill[]>([]);
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState<BillStatus | 'all'>('all');

  // View modes
  const [mode, setMode] = useState<'list' | 'create' | 'edit'>('list');
  const [editingBill, setEditingBill] = useState<Bill | null>(null);
  const [viewBill, setViewBill] = useState<Bill | null>(null);
  const [autoBillOpen, setAutoBillOpen] = useState(false);

  const reload = useCallback(() => setBills(loadBills()), []);
  useEffect(() => { reload(); }, [reload]);

  const handleSave = (bill: Bill) => {
    const all = loadBills();
    const idx = all.findIndex(b => b.id === bill.id);
    if (idx >= 0) all[idx] = bill;
    else all.unshift(bill);
    saveBills(all);
    toast.success(`${bill.billNumber} ${bill.status === 'draft' ? 'saved as draft' : 'submitted'} ✓`);
    reload();
    setMode('list');
    setEditingBill(null);
  };

  const handleDelete = (bill: Bill) => {
    if (!confirm(`Delete ${bill.billNumber}?`)) return;
    saveBills(loadBills().filter(b => b.id !== bill.id));
    toast.success('Bill deleted');
    reload();
  };

  const handleMarkPaid = (bill: Bill) => {
    const all = loadBills();
    const idx = all.findIndex(b => b.id === bill.id);
    if (idx >= 0) { all[idx].status = 'paid'; saveBills(all); reload(); toast.success('Marked as paid ✓'); }
  };

  const filtered = bills.filter(b => {
    const matchSearch = b.billNumber.toLowerCase().includes(search.toLowerCase()) ||
      b.vendor.name.toLowerCase().includes(search.toLowerCase());
    const matchStatus = filterStatus === 'all' || b.status === filterStatus;
    return matchSearch && matchStatus;
  });

  const totalBills = bills.length;
  const paidBills = bills.filter(b => b.status === 'paid').length;
  const pendingBills = bills.filter(b => b.status === 'pending').length;
  const totalAmount = bills.reduce((s, b) => s + b.total, 0);

  if (mode === 'create' || mode === 'edit') {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="bg-white border-b px-6 py-5">
          <div className="flex items-center gap-4">
            <button onClick={() => { setMode('list'); setEditingBill(null); }}
              className="p-2 rounded-lg hover:bg-gray-100 text-gray-500">
              <X size={18} />
            </button>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{mode === 'create' ? 'Create Bill' : `Edit ${editingBill?.billNumber}`}</h1>
              <p className="text-sm text-gray-500 mt-0.5">Fill in the bill details below</p>
            </div>
          </div>
        </div>
        <div className="px-6 py-6">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
            <BillForm
              initialData={editingBill}
              onSave={handleSave}
              onCancel={() => { setMode('list'); setEditingBill(null); }}
            />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b px-6 py-5">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Auto Bills</h1>
            <p className="text-sm text-gray-500 mt-0.5">Manage vendor bills — create from POs or manually</p>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={() => setAutoBillOpen(true)}
              className="flex items-center gap-2 px-4 py-2.5 bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold rounded-xl transition-colors">
              <Zap size={15} /> Auto Bill from PO
            </button>
            <button onClick={() => { setEditingBill(null); setMode('create'); }}
              className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-xl transition-colors">
              <Plus size={15} /> Create Bill
            </button>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="px-6 py-5 grid grid-cols-4 gap-4">
        {[
          { label: 'Total Bills', value: totalBills, icon: FileText, color: 'text-blue-600', bg: 'bg-blue-50' },
          { label: 'Paid', value: paidBills, icon: CheckCircle2, color: 'text-green-600', bg: 'bg-green-50' },
          { label: 'Pending', value: pendingBills, icon: Clock, color: 'text-yellow-600', bg: 'bg-yellow-50' },
          { label: 'Total Amount', value: `₹${totalAmount.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`, icon: DollarSign, color: 'text-purple-600', bg: 'bg-purple-50' },
        ].map(s => (
          <div key={s.label} className="bg-white rounded-2xl border border-gray-100 p-4 flex items-center gap-4 shadow-sm">
            <div className={`p-3 rounded-xl ${s.bg}`}><s.icon size={20} className={s.color} /></div>
            <div>
              <p className="text-xs text-gray-500 font-medium">{s.label}</p>
              <p className="text-xl font-bold text-gray-900 mt-0.5">{s.value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="px-6 pb-6">
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          {/* Toolbar */}
          <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
            <div className="flex items-center gap-2">
              {(['all', 'draft', 'pending', 'approved', 'paid', 'overdue'] as const).map(s => (
                <button key={s} onClick={() => setFilterStatus(s)}
                  className={`px-3 py-1.5 text-xs font-semibold rounded-full transition-colors ${filterStatus === s
                    ? 'bg-blue-600 text-white'
                    : 'text-gray-500 hover:bg-gray-100'}`}>
                  {s === 'all' ? 'All' : s.charAt(0).toUpperCase() + s.slice(1)}
                </button>
              ))}
            </div>
            <div className="flex items-center gap-2">
              <div className="relative">
                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <input value={search} onChange={e => setSearch(e.target.value)}
                  placeholder="Search bills…"
                  className="pl-8 pr-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 w-48" />
              </div>
              <button onClick={reload} className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg">
                <RefreshCw size={14} />
              </button>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 text-gray-600 text-xs">
                <tr>
                  <th className="px-5 py-3 text-left font-semibold">Bill No</th>
                  <th className="px-5 py-3 text-left font-semibold">Vendor</th>
                  <th className="px-5 py-3 text-left font-semibold">PO Ref</th>
                  <th className="px-5 py-3 text-right font-semibold">Amount (₹)</th>
                  <th className="px-5 py-3 text-center font-semibold">Status</th>
                  <th className="px-5 py-3 text-left font-semibold">Due Date</th>
                  <th className="px-5 py-3 text-center font-semibold">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {filtered.map(bill => (
                  <tr key={bill.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-5 py-3.5">
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-bold text-blue-600">{bill.billNumber}</span>
                        {bill.autoGenerated && (
                          <span className="text-[10px] px-1.5 py-0.5 bg-purple-100 text-purple-600 rounded-full font-semibold">AUTO</span>
                        )}
                      </div>
                    </td>
                    <td className="px-5 py-3.5 font-medium text-gray-800">{bill.vendor.name}</td>
                    <td className="px-5 py-3.5 font-mono text-xs text-gray-500">{bill.poReference || '—'}</td>
                    <td className="px-5 py-3.5 text-right font-bold text-gray-900">₹{fmt(bill.total)}</td>
                    <td className="px-5 py-3.5 text-center"><StatusBadge status={bill.status} /></td>
                    <td className="px-5 py-3.5 text-gray-500 text-xs">{bill.dueDate || '—'}</td>
                    <td className="px-5 py-3.5">
                      <div className="flex items-center justify-center gap-1.5">
                        <button onClick={() => setViewBill(bill)}
                          className="p-1.5 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded-lg" title="View">
                          <Eye size={14} />
                        </button>
                        <button onClick={() => { setEditingBill(bill); setMode('edit'); }}
                          className="p-1.5 text-gray-500 hover:text-orange-600 hover:bg-orange-50 rounded-lg" title="Edit">
                          <Edit2 size={14} />
                        </button>
                        <button onClick={() => generateBillPDF(bill)}
                          className="p-1.5 text-gray-500 hover:text-green-600 hover:bg-green-50 rounded-lg" title="Download PDF">
                          <Download size={14} />
                        </button>
                        {bill.status !== 'paid' && (
                          <button onClick={() => handleMarkPaid(bill)}
                            className="flex items-center gap-1 px-2 py-1 text-xs font-medium text-green-700 bg-green-50 hover:bg-green-100 rounded-lg">
                            <CheckCircle2 size={11} /> Paid
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr>
                    <td colSpan={7} className="px-5 py-14 text-center">
                      <div className="flex flex-col items-center gap-3 text-gray-400">
                        <FileText size={36} className="text-gray-200" />
                        <p className="text-sm font-medium">No bills found</p>
                        <p className="text-xs">Create a bill manually or generate from a PO</p>
                        <div className="flex gap-2 mt-1">
                          <button onClick={() => setAutoBillOpen(true)}
                            className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 text-white text-xs rounded-lg font-semibold">
                            <Zap size={11} /> Auto Bill from PO
                          </button>
                          <button onClick={() => setMode('create')}
                            className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white text-xs rounded-lg font-semibold">
                            <Plus size={11} /> Create Manually
                          </button>
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Modals */}
      {viewBill && <ViewBillModal bill={viewBill} onClose={() => setViewBill(null)} onDownload={generateBillPDF} />}
      {autoBillOpen && (
        <AutoBillFromPOModal
          onClose={() => setAutoBillOpen(false)}
          onCreated={(bill) => { handleSave(bill); setAutoBillOpen(false); }}
        />
      )}
    </div>
  );
}
