import { useState, useRef, useEffect, useCallback } from 'react';
import {
  Plus, X, Search, ChevronDown, Eye, Edit2, Trash2,
  CheckCircle2, Clock, AlertCircle, FileText, MoreVertical,
  Zap, User, Calendar, DollarSign, Building2, Tag,
  ArrowRight, Check, XCircle, Send, Printer, Download,
  ShoppingCart, Package, Receipt, RotateCcw, Info,
  HelpCircle, Paperclip, RefreshCw, Settings,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import {
  getOpenPOs, markPOBilled,
  type StoredPO,
} from '@/lib/purchaseStore';
import { getVendorNames } from '@/lib/vendorStore';

// ─── Types ────────────────────────────────────────────────
type BillStatus = 'draft' | 'pending_approval' | 'approved' | 'paid' | 'overdue' | 'rejected';

interface BillLineItem {
  id: number;
  itemName: string;
  account: string;
  quantity: number;
  rate: number;
  tax: string;
  discount: number;
  customerDetails: string;
}

interface Bill {
  id: number;
  billNumber: string;
  vendorName: string;
  poReference: string;
  billDate: string;
  dueDate: string;
  status: BillStatus;
  lineItems: BillLineItem[];
  notes: string;
  termsAndConditions: string;
  approvedBy: string;
  approvedAt: string;
  rejectedReason: string;
  autoGenerated: boolean;
  paymentTerms: string;
  subTotal: number;
  discount: number;
  tax: number;
  total: number;
}

// ─── Constants ────────────────────────────────────────────
// VENDORS loaded dynamically — see component useState below
const PAYMENT_TERMS = ['Due on Receipt', 'Net 15', 'Net 30', 'Net 45', 'Net 60'];
const TAX_RATES   = ['None', 'GST 5%', 'GST 12%', 'GST 18%', 'GST 28%'];
const ACCOUNTS    = ['Cost of Goods Sold', 'Office Supplies', 'Inventory Asset', 'Utilities', 'Repairs & Maintenance'];
const ITEMS_CATALOG = [
  { name: 'Rice Bags (50kg)',    rate: 2200 },
  { name: 'Wheat Flour (25kg)', rate: 850  },
  { name: 'Sunflower Oil (15L)',rate: 1650 },
  { name: 'Sugar (50kg)',       rate: 1900 },
  { name: 'Fertilizer (50kg)', rate: 1200 },
  { name: 'Pesticide (5L)',     rate: 780  },
];

// ─── Helpers ──────────────────────────────────────────────
let billCounter = 4;

function genBillNumber() {
  billCounter++;
  return `BILL-${String(billCounter).padStart(5, '0')}`;
}
function formatDate(d: string) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}
function formatINR(n: number) {
  return `₹${n.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
}
function addDays(d: string, days: number) {
  const dt = new Date(d); dt.setDate(dt.getDate() + days);
  return dt.toISOString().split('T')[0];
}
function calcTotals(items: BillLineItem[], discountPct: number) {
  const sub = items.reduce((s, i) => s + i.quantity * i.rate, 0);
  const disc = sub * discountPct / 100;
  const taxAmt = items.reduce((s, i) => {
    const pct = i.tax === 'GST 5%' ? 0.05 : i.tax === 'GST 12%' ? 0.12 : i.tax === 'GST 18%' ? 0.18 : i.tax === 'GST 28%' ? 0.28 : 0;
    return s + (i.quantity * i.rate * pct);
  }, 0);
  return { subTotal: sub, discount: disc, tax: taxAmt, total: sub - disc + taxAmt };
}

// ─── Demo data ────────────────────────────────────────────
const DEMO_BILLS: Bill[] = [
  {
    id: 1, billNumber: 'BILL-00001', vendorName: 'ABC Suppliers',
    poReference: 'PO-00001', billDate: '2026-05-01', dueDate: '2026-05-31',
    status: 'approved', autoGenerated: true, paymentTerms: 'Net 30',
    lineItems: [
      { id: 1, itemName: 'Rice Bags (50kg)', account: 'Cost of Goods Sold', quantity: 20, rate: 2200, tax: 'GST 5%', discount: 0, customerDetails: '' },
      { id: 2, itemName: 'Wheat Flour (25kg)', account: 'Cost of Goods Sold', quantity: 15, rate: 850, tax: 'GST 5%', discount: 0, customerDetails: '' },
    ],
    notes: 'Auto-generated from PO-00001', termsAndConditions: 'Payment within 30 days.',
    approvedBy: 'Admin', approvedAt: '2026-05-02T10:30:00', rejectedReason: '',
    subTotal: 56750, discount: 0, tax: 2837.5, total: 59587.5,
  },
  {
    id: 2, billNumber: 'BILL-00002', vendorName: 'XYZ Traders',
    poReference: 'PO-00002', billDate: '2026-05-05', dueDate: '2026-05-20',
    status: 'pending_approval', autoGenerated: true, paymentTerms: 'Net 15',
    lineItems: [
      { id: 1, itemName: 'Sunflower Oil (15L)', account: 'Cost of Goods Sold', quantity: 10, rate: 1650, tax: 'GST 12%', discount: 0, customerDetails: '' },
    ],
    notes: 'Auto-generated from PO-00002', termsAndConditions: '',
    approvedBy: '', approvedAt: '', rejectedReason: '',
    subTotal: 16500, discount: 0, tax: 1980, total: 18480,
  },
  {
    id: 3, billNumber: 'BILL-00003', vendorName: 'Global Imports',
    poReference: '', billDate: '2026-05-08', dueDate: '2026-05-08',
    status: 'overdue', autoGenerated: false, paymentTerms: 'Due on Receipt',
    lineItems: [
      { id: 1, itemName: 'Fertilizer (50kg)', account: 'Cost of Goods Sold', quantity: 30, rate: 1200, tax: 'GST 18%', discount: 0, customerDetails: '' },
    ],
    notes: 'Manual bill entry', termsAndConditions: '',
    approvedBy: '', approvedAt: '', rejectedReason: '',
    subTotal: 36000, discount: 0, tax: 6480, total: 42480,
  },
];

// ─── useOutsideClick ──────────────────────────────────────
function useOutsideClick(ref: React.RefObject<HTMLElement | null>, handler: () => void) {
  useEffect(() => {
    const fn = (e: MouseEvent) => {
      if (!ref.current || ref.current.contains(e.target as Node)) return;
      handler();
    };
    document.addEventListener('mousedown', fn);
    return () => document.removeEventListener('mousedown', fn);
  }, [ref, handler]);
}

// ─── Status Badge ─────────────────────────────────────────
function StatusBadge({ status }: { status: BillStatus }) {
  const map: Record<BillStatus, { label: string; cls: string; icon: React.ReactNode }> = {
    draft:            { label: 'Draft',            cls: 'bg-gray-100 text-gray-600',    icon: <FileText className="w-3 h-3" /> },
    pending_approval: { label: 'Pending Approval', cls: 'bg-amber-100 text-amber-700',  icon: <Clock className="w-3 h-3" /> },
    approved:         { label: 'Approved',         cls: 'bg-green-100 text-green-700',  icon: <CheckCircle2 className="w-3 h-3" /> },
    paid:             { label: 'Paid',             cls: 'bg-blue-100 text-blue-700',    icon: <Check className="w-3 h-3" /> },
    overdue:          { label: 'Overdue',          cls: 'bg-red-100 text-red-600',      icon: <AlertCircle className="w-3 h-3" /> },
    rejected:         { label: 'Rejected',         cls: 'bg-rose-100 text-rose-700',    icon: <XCircle className="w-3 h-3" /> },
  };
  const s = map[status];
  return (
    <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold ${s.cls}`}>
      {s.icon}{s.label}
    </span>
  );
}

// ─── SimpleSelect ─────────────────────────────────────────
function SimpleSelect({ value, onChange, options, placeholder = 'Select…', className = '' }: {
  value: string; onChange: (v: string) => void;
  options: string[]; placeholder?: string; className?: string;
}) {
  return (
    <div className={`relative ${className}`}>
      <select value={value} onChange={e => onChange(e.target.value)}
        className="w-full h-9 pl-3 pr-8 border border-gray-300 rounded-md bg-white text-sm text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 appearance-none">
        <option value="">{placeholder}</option>
        {options.map(o => <option key={o}>{o}</option>)}
      </select>
      <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
    </div>
  );
}

// ─── Auto-Generate Modal ──────────────────────────────────
function AutoGenerateModal({ onClose, onGenerate }: {
  onClose: () => void;
  onGenerate: (po: StoredPO) => void;
}) {
  // Read open POs from the shared store (includes both demo + user-created)
  const [openPOs] = useState<StoredPO[]>(() => getOpenPOs());
  const [selectedPO, setSelectedPO] = useState<StoredPO | null>(null);
  const [search, setSearch] = useState('');

  const filtered = openPOs.filter(po =>
    po.poNumber.toLowerCase().includes(search.toLowerCase()) ||
    po.vendorName.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg flex flex-col overflow-hidden" style={{ maxHeight: '90vh' }}>

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-blue-100 flex items-center justify-center">
              <Zap className="w-4.5 h-4.5 text-blue-600" />
            </div>
            <div>
              <h2 className="text-base font-bold text-gray-900">Auto-Generate Bill from PO</h2>
              <p className="text-xs text-gray-400">Select an open purchase order</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Info banner */}
        <div className="mx-6 mt-4 flex items-start gap-2.5 p-3 bg-blue-50 border border-blue-200 rounded-xl shrink-0">
          <Info className="w-4 h-4 text-blue-500 mt-0.5 shrink-0" />
          <p className="text-xs text-blue-700 leading-relaxed">
            Bill will be auto-created with <strong>all line items, vendor details and amounts</strong> pre-filled
            from the selected PO. It goes to <strong>Pending Approval</strong> before payment.
          </p>
        </div>

        {/* Search */}
        <div className="px-6 pt-4 shrink-0">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
            <input value={search} onChange={e => setSearch(e.target.value)}
              placeholder="Search by PO number or vendor…"
              className="w-full h-8 pl-9 pr-3 text-xs border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400 bg-white" />
          </div>
        </div>

        {/* PO list */}
        <div className="flex-1 overflow-y-auto px-6 py-3 space-y-2">
          {filtered.length === 0 ? (
            <div className="py-10 text-center">
              <ShoppingCart className="w-8 h-8 text-gray-200 mx-auto mb-2" />
              <p className="text-sm text-gray-400 font-medium">No open purchase orders found</p>
              <p className="text-xs text-gray-400 mt-0.5">Create a PO first in Purchase Orders page</p>
            </div>
          ) : filtered.map(po => {
            const selected = selectedPO?.poNumber === po.poNumber;
            const itemCount = po.items.filter(i => i.itemName).length;
            return (
              <button key={po.poNumber} type="button"
                onClick={() => setSelectedPO(po)}
                className={`w-full text-left p-3.5 border rounded-xl transition-all ${
                  selected
                    ? 'border-blue-500 bg-blue-50 ring-1 ring-blue-500/30'
                    : 'border-gray-200 hover:border-blue-300 hover:bg-gray-50/80'
                }`}>
                <div className="flex items-start justify-between gap-3">
                  {/* Radio indicator */}
                  <div className={`mt-0.5 w-4 h-4 rounded-full border-2 shrink-0 flex items-center justify-center transition-colors ${
                    selected ? 'border-blue-500 bg-blue-500' : 'border-gray-300'
                  }`}>
                    {selected && <div className="w-2 h-2 rounded-full bg-white" />}
                  </div>

                  {/* PO info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className={`text-sm font-bold font-mono ${selected ? 'text-blue-700' : 'text-gray-800'}`}>
                        {po.poNumber}
                      </span>
                      <span className="px-1.5 py-0.5 bg-green-100 text-green-700 text-xs font-semibold rounded-full">
                        Open
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 mt-0.5">{po.vendorName}</p>
                    <div className="flex items-center gap-3 mt-1.5 text-xs text-gray-400">
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3 h-3" /> {po.date}
                      </span>
                      <span className="flex items-center gap-1">
                        <Package className="w-3 h-3" /> {itemCount} item{itemCount !== 1 ? 's' : ''}
                      </span>
                    </div>
                    {/* Item preview chips */}
                    {po.items.filter(i => i.itemName).length > 0 && (
                      <div className="flex flex-wrap gap-1 mt-2">
                        {po.items.filter(i => i.itemName).slice(0, 3).map((item, i) => (
                          <span key={i}
                            className="inline-flex items-center px-1.5 py-0.5 bg-gray-100 text-gray-600 text-[10px] rounded-md font-medium">
                            {item.itemName} × {item.quantity}
                          </span>
                        ))}
                        {po.items.filter(i => i.itemName).length > 3 && (
                          <span className="inline-flex items-center px-1.5 py-0.5 bg-gray-100 text-gray-500 text-[10px] rounded-md">
                            +{po.items.filter(i => i.itemName).length - 3} more
                          </span>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Total */}
                  <div className="text-right shrink-0">
                    <p className="text-sm font-bold text-gray-800">
                      ₹{po.total.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                    </p>
                    <p className="text-xs text-gray-400">{po.paymentTerms}</p>
                  </div>
                </div>
              </button>
            );
          })}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-200 flex items-center gap-3 shrink-0">
          <Button disabled={!selectedPO}
            onClick={() => { onGenerate(selectedPO!); onClose(); }}
            className="flex-1 h-9 text-sm bg-blue-600 hover:bg-blue-700 text-white font-semibold disabled:opacity-40">
            <Zap className="w-4 h-4 mr-1.5" /> Generate Bill from {selectedPO?.poNumber ?? 'PO'}
          </Button>
          <Button variant="outline" onClick={onClose} className="h-9 px-4 text-sm border-gray-300 text-gray-600">
            Cancel
          </Button>
        </div>
      </div>
    </div>
  );
}

// ─── Print helper ─────────────────────────────────────────
function printBill(bill: Bill) {
  const fmt = (n: number) =>
    '₹' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fmtDate = (d: string) => {
    if (!d) return '—';
    const [y, m, day] = d.split('-');
    return `${day}/${m}/${y}`;
  };

  const rows = bill.lineItems.map((item, i) => `
    <tr style="border-bottom:1px solid #ebebeb;">
      <td style="padding:11px 14px;color:#555;">${i + 1}</td>
      <td style="padding:11px 14px;"><strong style="font-size:13px;color:#111;">${item.itemName || '—'}</strong></td>
      <td style="padding:11px 14px;font-size:13px;color:#444;">${item.account || '—'}</td>
      <td style="padding:11px 14px;text-align:right;font-size:13px;font-weight:700;color:#111;">${item.quantity}</td>
      <td style="padding:11px 14px;text-align:right;font-size:13px;color:#333;">${fmt(item.rate)}</td>
      <td style="padding:11px 14px;text-align:right;font-size:12px;color:#555;">${item.tax || '—'}</td>
      <td style="padding:11px 14px;text-align:right;font-size:13px;font-weight:700;color:#111;">${fmt(item.quantity * item.rate * (1 - (item.discount ?? 0) / 100))}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${bill.billNumber}</title>
  <style>
    @page { size: A4 portrait; margin: 0; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: Arial, Helvetica, sans-serif;
      font-size: 13px; color: #1a1a1a; background: #fff;
      padding: 40px 48px 90px 48px;
    }
    .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:22px; }
    .co-name { font-size:17px; font-weight:900; color:#111; letter-spacing:-0.3px; }
    .co-sub  { font-size:11px; color:#888; margin-top:3px; }
    .bill-title { text-align:right; }
    .bill-num   { font-size:24px; font-weight:900; color:#111; letter-spacing:-0.5px; }
    .bill-status{ font-size:11px; color:#666; margin-top:5px; text-transform:uppercase; letter-spacing:1px; }
    .divider { border:none; border-top:1.5px solid #e0e0e0; margin:0 0 22px 0; }
    .info-grid { display:grid; grid-template-columns:1fr 1fr; gap:14px 40px; margin-bottom:28px; }
    .info-block .lbl {
      font-size:9.5px; font-weight:700; text-transform:uppercase;
      letter-spacing:0.9px; color:#aaa; margin-bottom:4px;
    }
    .info-block .val       { font-size:13px; font-weight:700; color:#111; }
    .info-block .val-light { font-size:12px; color:#555; margin-top:1px; }
    table { width:100%; border-collapse:collapse; }
    thead tr { background:#1a1a1a; }
    thead th {
      padding:11px 14px; color:#fff; font-size:11px;
      font-weight:700; text-transform:uppercase; letter-spacing:0.5px; text-align:left;
    }
    thead th.r { text-align:right; }
    tbody tr:last-child { border-bottom:none; }
    .totals { border-top:1.5px solid #ddd; }
    .total-row {
      display:flex; justify-content:flex-end; align-items:center;
      padding:9px 14px; border-bottom:1px solid #f2f2f2; gap:80px;
    }
    .total-row .tl { font-size:12px; color:#666; min-width:100px; text-align:right; }
    .total-row .tv { font-size:13px; font-weight:700; color:#111; min-width:120px; text-align:right; }
    .total-row.grand { border-top:2px solid #ccc; border-bottom:none; padding-top:12px; }
    .total-row.grand .tl { font-size:14px; font-weight:900; color:#111; }
    .total-row.grand .tv { font-size:15px; font-weight:900; color:#111; }
    .notes {
      margin-top:24px; padding:12px 16px;
      background:#f9fafb; border:1px solid #e5e7eb; border-radius:8px; font-size:12px; color:#555;
    }
    .page-footer {
      position:fixed; bottom:22px; left:48px; right:48px;
      display:flex; justify-content:space-between;
      font-size:10px; color:#bbb; border-top:1px solid #eee; padding-top:6px;
    }
  </style>
</head>
<body>

  <div class="header">
    <div>
      <div class="co-name">Farmers Factory ERP</div>
      <div class="co-sub">Tax Bill / Purchase Invoice</div>
    </div>
    <div class="bill-title">
      <div class="bill-num">${bill.billNumber}</div>
      <div class="bill-status">${bill.status.replace(/_/g, ' ')}</div>
    </div>
  </div>

  <hr class="divider"/>

  <div class="info-grid">
    <div class="info-block">
      <div class="lbl">Vendor</div>
      <div class="val">${bill.vendorName}</div>
    </div>
    <div class="info-block">
      <div class="lbl">PO Reference</div>
      <div class="val">${bill.poReference || '—'}</div>
    </div>
    <div class="info-block">
      <div class="lbl">Bill Date</div>
      <div class="val">${fmtDate(bill.billDate)}</div>
    </div>
    <div class="info-block">
      <div class="lbl">Due Date</div>
      <div class="val">${fmtDate(bill.dueDate)}</div>
    </div>
    <div class="info-block">
      <div class="lbl">Payment Terms</div>
      <div class="val">${bill.paymentTerms || '—'}</div>
    </div>
    <div class="info-block">
      <div class="lbl">Approved By</div>
      <div class="val">${bill.approvedBy || '—'}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:36px;">#</th>
        <th>Item</th>
        <th>Account</th>
        <th class="r" style="width:60px;">Qty</th>
        <th class="r" style="width:110px;">Rate</th>
        <th class="r" style="width:80px;">Tax</th>
        <th class="r" style="width:130px;">Amount</th>
      </tr>
    </thead>
    <tbody>${rows || `<tr><td colspan="7" style="text-align:center;color:#aaa;padding:18px;">No items</td></tr>`}</tbody>
  </table>

  <div class="totals">
    <div class="total-row">
      <span class="tl">Sub Total</span>
      <span class="tv">${fmt(bill.subTotal)}</span>
    </div>
    <div class="total-row">
      <span class="tl">Tax</span>
      <span class="tv">${fmt(bill.tax)}</span>
    </div>
    ${bill.discount > 0 ? `
    <div class="total-row">
      <span class="tl">Discount</span>
      <span class="tv">- ${fmt(bill.discount)}</span>
    </div>` : ''}
    <div class="total-row grand">
      <span class="tl">Total</span>
      <span class="tv">${fmt(bill.total)}</span>
    </div>
  </div>

  ${bill.notes ? `<div class="notes"><strong>Notes:</strong> ${bill.notes}</div>` : ''}

  <div class="page-footer">
    <span>Farmers Factory ERP · ${bill.billNumber}</span>
    <span>Page 1</span>
  </div>

  <script>
    window.onload = function() { window.print(); window.onafterprint = function() { window.close(); }; };
  </script>
</body>
</html>`;

  const win = window.open('', '_blank', 'width=794,height=1123,scrollbars=yes');
  if (!win) { toast.error('Allow pop-ups to use Print'); return; }
  win.document.write(html);
  win.document.close();
}

// ─── Download PDF helper ───────────────────────────────────
async function downloadBillPDF(bill: Bill) {
  const fmt = (n: number) =>
    '₹' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fmtD = (d: string) => {
    if (!d) return '—';
    const parts = d.split('-');
    return parts.length === 3 ? `${parts[2]}/${parts[1]}/${parts[0]}` : d;
  };

  try {
    const { jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const W = doc.internal.pageSize.getWidth();

    // ── Header — white background, dark text ──────────
    doc.setTextColor(17, 24, 39);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Farmers Factory ERP', 14, 14);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text('Tax Bill / Purchase Invoice', 14, 20);

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(17, 24, 39);
    doc.text(bill.billNumber, W - 14, 14, { align: 'right' });

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(bill.status.replace(/_/g, ' ').toUpperCase(), W - 14, 20, { align: 'right' });

    // ── Divider ────────────────────────────────────────
    doc.setDrawColor(210, 210, 210);
    doc.setLineWidth(0.4);
    doc.line(14, 24, W - 14, 24);

    // ── Meta grid ─────────────────────────────────────
    const meta: [string, string][] = [
      ['VENDOR',         bill.vendorName],
      ['PO REFERENCE',   bill.poReference || '—'],
      ['BILL DATE',      fmtD(bill.billDate)],
      ['DUE DATE',       fmtD(bill.dueDate)],
      ['PAYMENT TERMS',  bill.paymentTerms || '—'],
      ['APPROVED BY',    bill.approvedBy   || '—'],
    ];

    let y = 32;
    for (let i = 0; i < meta.length; i += 2) {
      const [l1, v1] = meta[i];
      const [l2, v2] = meta[i + 1] ?? ['', ''];

      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(170, 170, 170);
      doc.text(l1, 14, y);
      if (l2) doc.text(l2, W / 2, y);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(17, 24, 39);
      doc.text(v1, 14, y + 5.5);
      if (v2) doc.text(v2, W / 2, y + 5.5);

      y += 13;
    }

    // ── Line-items table — dark header ────────────────
    const tableBody = bill.lineItems.map((item, i) => [
      String(i + 1),
      item.itemName || '—',
      item.account  || '—',
      String(item.quantity),
      fmt(item.rate),
      item.tax || '—',
      fmt(item.quantity * item.rate * (1 - (item.discount ?? 0) / 100)),
    ]);

    autoTable(doc, {
      startY: y + 2,
      head: [['#', 'Item', 'Account', 'Qty', 'Rate', 'Tax', 'Amount']],
      body: tableBody,
      headStyles: {
        fillColor:  [26, 26, 26],      // dark #1a1a1a — same as reference
        textColor:  [255, 255, 255],
        fontStyle:  'bold',
        fontSize:   7.5,
      },
      bodyStyles:          { fontSize: 9, textColor: [17, 24, 39] },
      alternateRowStyles:  { fillColor: [252, 252, 252] },
      columnStyles: {
        0: { cellWidth: 8 },
        3: { halign: 'right' },
        4: { halign: 'right' },
        5: { halign: 'right' },
        6: { halign: 'right', fontStyle: 'bold' },
      },
      margin:          { left: 14, right: 14 },
      tableLineColor:  [230, 230, 230],
      tableLineWidth:  0.2,
    });

    // ── Totals — no blue, plain text ──────────────────
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const finalY: number = (doc as any).lastAutoTable?.finalY ?? y + 30;
    const totX = W - 14;
    const lblX = W - 65;

    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.4);
    doc.line(lblX - 2, finalY + 3, totX, finalY + 3);

    const totRows: [string, string][] = [
      ['Sub Total', fmt(bill.subTotal)],
      ['Tax',       fmt(bill.tax)],
      ...(bill.discount > 0 ? [['Discount', `- ${fmt(bill.discount)}`] as [string, string]] : []),
    ];

    let ty = finalY + 9;
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    for (const [lbl, val] of totRows) {
      doc.setTextColor(110, 110, 110);
      doc.text(lbl, lblX, ty);
      doc.setTextColor(17, 24, 39);
      doc.text(val, totX, ty, { align: 'right' });
      doc.setDrawColor(235, 235, 235);
      doc.line(lblX - 2, ty + 2.5, totX, ty + 2.5);
      ty += 8;
    }

    // Grand total — bold dark text, no blue fill
    doc.setDrawColor(160, 160, 160);
    doc.setLineWidth(0.6);
    doc.line(lblX - 2, ty - 2, totX, ty - 2);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(17, 24, 39);
    doc.text('Total', lblX, ty + 5);
    doc.text(fmt(bill.total), totX, ty + 5, { align: 'right' });

    // ── Notes ─────────────────────────────────────────
    if (bill.notes) {
      const ny = ty + 14;
      doc.setFillColor(249, 250, 251);
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.3);
      doc.roundedRect(14, ny, W - 28, 12, 1.5, 1.5, 'FD');
      doc.setTextColor(110, 110, 110);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.text('Notes:', 18, ny + 7);
      doc.setFont('helvetica', 'normal');
      doc.text(bill.notes, 33, ny + 7);
    }

    // ── Footer ────────────────────────────────────────
    const pageH = doc.internal.pageSize.getHeight();
    doc.setDrawColor(210, 210, 210);
    doc.setLineWidth(0.3);
    doc.line(14, pageH - 14, W - 14, pageH - 14);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(170, 170, 170);
    doc.text(`Farmers Factory ERP · ${bill.billNumber}`, 14, pageH - 9);
    doc.text('Page 1', W - 14, pageH - 9, { align: 'right' });

    doc.save(`${bill.billNumber}.pdf`);
    toast.success(`${bill.billNumber}.pdf downloaded`);
  } catch (err) {
    console.error(err);
    toast.error('Could not generate PDF');
  }
}

// ─── Reject Modal ─────────────────────────────────────────
function RejectModal({ bill, onClose, onReject }: {
  bill: Bill; onClose: () => void; onReject: (id: number, reason: string) => void;
}) {
  const [reason, setReason] = useState('');
  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 backdrop-blur-sm">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm mx-4">
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
          <h3 className="text-base font-bold text-gray-900">Reject Bill</h3>
          <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100">
            <X className="w-4 h-4" />
          </button>
        </div>
        <div className="p-5 space-y-3">
          <p className="text-sm text-gray-600">Rejecting <span className="font-semibold">{bill.billNumber}</span>. Please provide a reason.</p>
          <textarea value={reason} onChange={e => setReason(e.target.value)}
            rows={3} placeholder="Enter rejection reason…"
            className="w-full resize-none px-3 py-2 text-sm border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/20 focus:border-red-400 bg-white" />
        </div>
        <div className="px-5 py-4 border-t border-gray-200 flex gap-3">
          <Button onClick={() => { if (!reason.trim()) { toast.error('Please enter a reason'); return; } onReject(bill.id, reason); onClose(); }}
            className="flex-1 h-9 text-sm bg-red-600 hover:bg-red-700 text-white font-semibold">
            <XCircle className="w-4 h-4 mr-1.5" /> Reject
          </Button>
          <Button variant="outline" onClick={onClose} className="h-9 px-4 text-sm border-gray-300">Cancel</Button>
        </div>
      </div>
    </div>
  );
}

// ─── Bill View / Approval Modal ───────────────────────────
function BillViewModal({ bill, onClose, onApprove, onReject, onEdit }: {
  bill: Bill;
  onClose: () => void;
  onApprove: (id: number) => void;
  onReject: (id: number) => void;
  onEdit: (bill: Bill) => void;
}) {
  const [showReject, setShowReject] = useState(false);
  const totals = calcTotals(bill.lineItems, 0);

  return (
    <>
      {showReject && (
        <RejectModal bill={bill} onClose={() => setShowReject(false)}
          onReject={(id, reason) => { onReject(id); onClose(); toast.success('Bill rejected'); }} />
      )}

      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl flex flex-col overflow-hidden" style={{ maxHeight: '92vh' }}>

          {/* Header */}
          <div className="flex items-center justify-between px-7 py-5 border-b border-gray-200 shrink-0">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center">
                <Receipt className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h2 className="text-lg font-bold text-gray-900">{bill.billNumber}</h2>
                  <StatusBadge status={bill.status} />
                  {bill.autoGenerated && (
                    <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-purple-100 text-purple-700 text-xs font-semibold rounded-full">
                      <Zap className="w-3 h-3" /> Auto
                    </span>
                  )}
                </div>
                <p className="text-xs text-gray-400 mt-0.5">
                  {bill.poReference ? `From ${bill.poReference} · ` : ''}{bill.vendorName}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => printBill(bill)}
                className="p-2 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                title="Print bill">
                <Printer className="w-4 h-4" />
              </button>
              <button
                onClick={() => downloadBillPDF(bill)}
                className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                title="Download PDF">
                <Download className="w-4 h-4" />
              </button>
              {(bill.status === 'draft' || bill.status === 'pending_approval') && (
                <button onClick={() => { onClose(); onEdit(bill); }}
                  className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg" title="Edit">
                  <Edit2 className="w-4 h-4" />
                </button>
              )}
              <button onClick={onClose} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto px-7 py-6 space-y-6">

            {/* Approval banner */}
            {bill.status === 'pending_approval' && (
              <div className="flex items-center justify-between p-4 bg-amber-50 border border-amber-200 rounded-xl">
                <div className="flex items-center gap-3">
                  <Clock className="w-5 h-5 text-amber-600 shrink-0" />
                  <div>
                    <p className="text-sm font-semibold text-amber-800">Awaiting Your Approval</p>
                    <p className="text-xs text-amber-600 mt-0.5">
                      Please review all line items and amounts carefully before approving.
                    </p>
                  </div>
                </div>
                <div className="flex gap-2 shrink-0">
                  <Button onClick={() => { onApprove(bill.id); onClose(); }}
                    className="h-8 px-4 text-xs bg-green-600 hover:bg-green-700 text-white font-semibold">
                    <CheckCircle2 className="w-3.5 h-3.5 mr-1" /> Approve
                  </Button>
                  <Button variant="outline" onClick={() => setShowReject(true)}
                    className="h-8 px-3 text-xs border-red-300 text-red-600 hover:bg-red-50">
                    <XCircle className="w-3.5 h-3.5 mr-1" /> Reject
                  </Button>
                </div>
              </div>
            )}

            {/* Approved banner */}
            {bill.status === 'approved' && (
              <div className="flex items-center gap-3 p-4 bg-green-50 border border-green-200 rounded-xl">
                <CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" />
                <div>
                  <p className="text-sm font-semibold text-green-800">Bill Approved</p>
                  <p className="text-xs text-green-600 mt-0.5">
                    Approved by <span className="font-semibold">{bill.approvedBy}</span>
                    {bill.approvedAt ? ` on ${formatDate(bill.approvedAt.split('T')[0])}` : ''}
                  </p>
                </div>
              </div>
            )}

            {/* Rejected banner */}
            {bill.status === 'rejected' && (
              <div className="flex items-center gap-3 p-4 bg-red-50 border border-red-200 rounded-xl">
                <XCircle className="w-5 h-5 text-red-500 shrink-0" />
                <div>
                  <p className="text-sm font-semibold text-red-700">Bill Rejected</p>
                  <p className="text-xs text-red-600 mt-0.5">Reason: {bill.rejectedReason || '—'}</p>
                </div>
              </div>
            )}

            {/* Meta grid */}
            <div className="grid grid-cols-2 gap-x-8 gap-y-4">
              {[
                { label: 'Vendor',         value: bill.vendorName,   icon: <Building2 className="w-4 h-4 text-gray-400" /> },
                { label: 'Bill Number',    value: bill.billNumber,   icon: <Receipt className="w-4 h-4 text-gray-400" /> },
                { label: 'Bill Date',      value: formatDate(bill.billDate), icon: <Calendar className="w-4 h-4 text-gray-400" /> },
                { label: 'Due Date',       value: formatDate(bill.dueDate),  icon: <Calendar className="w-4 h-4 text-gray-400" /> },
                { label: 'PO Reference',   value: bill.poReference || '—', icon: <ShoppingCart className="w-4 h-4 text-gray-400" /> },
                { label: 'Payment Terms',  value: bill.paymentTerms, icon: <DollarSign className="w-4 h-4 text-gray-400" /> },
              ].map(f => (
                <div key={f.label} className="flex items-center gap-3">
                  {f.icon}
                  <div>
                    <p className="text-xs text-gray-400 font-medium">{f.label}</p>
                    <p className="text-sm font-semibold text-gray-800 mt-0.5">{f.value}</p>
                  </div>
                </div>
              ))}
            </div>

            {/* Line items */}
            <div>
              <p className="text-sm font-bold text-gray-800 mb-3">Line Items</p>
              <div className="border border-gray-200 rounded-xl overflow-hidden">
                <table className="w-full">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      <th className="px-4 py-2.5 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Item</th>
                      <th className="px-4 py-2.5 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Account</th>
                      <th className="px-4 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Qty</th>
                      <th className="px-4 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Rate</th>
                      <th className="px-4 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Tax</th>
                      <th className="px-4 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Amount</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {bill.lineItems.map(item => (
                      <tr key={item.id} className="hover:bg-blue-50/20 transition-colors">
                        <td className="px-4 py-3 text-sm font-medium text-gray-800">{item.itemName}</td>
                        <td className="px-4 py-3 text-sm text-gray-500">{item.account}</td>
                        <td className="px-4 py-3 text-sm text-gray-700 text-right">{item.quantity}</td>
                        <td className="px-4 py-3 text-sm text-gray-700 text-right">{formatINR(item.rate)}</td>
                        <td className="px-4 py-3 text-xs text-right">
                          <span className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded-full font-medium">{item.tax || 'None'}</span>
                        </td>
                        <td className="px-4 py-3 text-sm font-semibold text-gray-800 text-right">
                          {formatINR(item.quantity * item.rate)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Totals */}
            <div className="flex justify-end">
              <div className="w-72 bg-gray-50 rounded-xl border border-gray-200 overflow-hidden">
                <div className="px-5 py-3 flex justify-between border-b border-gray-100">
                  <span className="text-sm text-gray-600">Sub Total</span>
                  <span className="text-sm font-semibold text-gray-800">{formatINR(bill.subTotal)}</span>
                </div>
                {bill.discount > 0 && (
                  <div className="px-5 py-3 flex justify-between border-b border-gray-100">
                    <span className="text-sm text-gray-600">Discount</span>
                    <span className="text-sm text-red-500">− {formatINR(bill.discount)}</span>
                  </div>
                )}
                <div className="px-5 py-3 flex justify-between border-b border-gray-100">
                  <span className="text-sm text-gray-600">Tax</span>
                  <span className="text-sm text-gray-700">{formatINR(bill.tax)}</span>
                </div>
                <div className="px-5 py-4 flex justify-between bg-white">
                  <span className="text-base font-bold text-gray-900">Total</span>
                  <span className="text-base font-bold text-blue-600">{formatINR(bill.total)}</span>
                </div>
              </div>
            </div>

            {/* Notes */}
            {bill.notes && (
              <div>
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Notes</p>
                <p className="text-sm text-gray-700 bg-gray-50 rounded-xl px-4 py-3 border border-gray-100">{bill.notes}</p>
              </div>
            )}
          </div>

          {/* Footer actions */}
          <div className="px-7 py-4 border-t border-gray-200 flex items-center justify-between shrink-0 bg-white">
            <Button variant="outline" onClick={onClose} className="h-9 px-4 text-sm border-gray-300 text-gray-600">
              Close
            </Button>
            {bill.status === 'pending_approval' && (
              <div className="flex gap-2">
                <Button onClick={() => setShowReject(true)}
                  variant="outline" className="h-9 px-4 text-sm border-red-200 text-red-600 hover:bg-red-50">
                  <XCircle className="w-4 h-4 mr-1.5" /> Reject
                </Button>
                <Button onClick={() => { onApprove(bill.id); onClose(); }}
                  className="h-9 px-5 text-sm bg-green-600 hover:bg-green-700 text-white font-semibold">
                  <CheckCircle2 className="w-4 h-4 mr-1.5" /> Approve Bill
                </Button>
              </div>
            )}
            {bill.status === 'approved' && (
              <Button className="h-9 px-5 text-sm bg-blue-600 hover:bg-blue-700 text-white font-semibold">
                <DollarSign className="w-4 h-4 mr-1.5" /> Record Payment
              </Button>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

// ─── Bill Form (New / Edit) ───────────────────────────────
function BillForm({ onClose, onSave, editBill }: {
  onClose: () => void;
  onSave: (bill: Bill) => void;
  editBill?: Bill | null;
}) {
  const today = new Date().toISOString().split('T')[0];

  // Vendor names from store
  const [VENDORS, setVENDORS] = useState<string[]>(() => getVendorNames());
  useEffect(() => { setVENDORS(getVendorNames()); }, []);

  // Generate bill number once on mount
  const [billNo] = useState(() => editBill?.billNumber ?? genBillNumber());

  const [form, setForm] = useState({
    vendorName:      editBill?.vendorName    ?? '',
    orderNumber:     '',
    billDate:        editBill?.billDate      ?? today,
    dueDate:         editBill?.dueDate       ?? addDays(today, 30),
    paymentTerms:    editBill?.paymentTerms  ?? 'Net 30',
    accountsPayable: 'Accounts Payable',
    subject:         '',
    tdsOrTcs:        'tds',
    selectedTax:     '',
    adjustment:      '0',
    notes:           editBill?.notes         ?? '',
  });

  const [lineItems, setLineItems] = useState<BillLineItem[]>(
    editBill?.lineItems ?? [{
      id: 1, itemName: '', account: '', quantity: 1, rate: 0, tax: 'None', discount: 0, customerDetails: ''
    }]
  );

  const set = (k: string, v: string) => setForm(p => ({ ...p, [k]: v }));

  // When payment terms change → auto-update due date
  const handlePaymentTermsChange = (v: string) => {
    const daysMap: Record<string, number> = {
      'Due on Receipt': 0, 'Net 15': 15, 'Net 30': 30, 'Net 45': 45, 'Net 60': 60,
    };
    set('paymentTerms', v);
    if (daysMap[v] !== undefined) set('dueDate', addDays(form.billDate, daysMap[v]));
  };

  const addRow = () => setLineItems(p => [...p, {
    id: Date.now(), itemName: '', account: '', quantity: 1, rate: 0, tax: 'None', discount: 0, customerDetails: ''
  }]);
  const removeRow = (id: number) => { if (lineItems.length > 1) setLineItems(p => p.filter(r => r.id !== id)); };
  const setCell = (id: number, k: keyof BillLineItem, v: string | number) =>
    setLineItems(p => p.map(r => r.id === id ? { ...r, [k]: v } : r));

  // Compute totals
  const subTotal = lineItems.reduce((s, i) => s + i.quantity * i.rate * (1 - i.discount / 100), 0);
  const taxAmt   = lineItems.reduce((s, i) => {
    const pct = i.tax === 'GST 5%' ? 0.05 : i.tax === 'GST 12%' ? 0.12 : i.tax === 'GST 18%' ? 0.18 : i.tax === 'GST 28%' ? 0.28 : 0;
    return s + (i.quantity * i.rate * (1 - i.discount / 100) * pct);
  }, 0);
  const adj   = parseFloat(form.adjustment) || 0;
  const total = subTotal + taxAmt + adj;

  const handleSave = (status: BillStatus) => {
    if (!form.vendorName) { toast.error('Vendor is required'); return; }
    const bill: Bill = {
      id: editBill?.id ?? Date.now(),
      billNumber: billNo,
      vendorName: form.vendorName,
      poReference: editBill?.poReference ?? '',
      billDate: form.billDate,
      dueDate: form.dueDate,
      paymentTerms: form.paymentTerms,
      status,
      lineItems,
      notes: form.notes,
      termsAndConditions: '',
      approvedBy: editBill?.approvedBy ?? '',
      approvedAt: editBill?.approvedAt ?? '',
      rejectedReason: '',
      autoGenerated: editBill?.autoGenerated ?? false,
      subTotal, discount: 0, tax: taxAmt, total,
    };
    onSave(bill);
    toast.success(status === 'draft' ? 'Bill saved as draft' : 'Bill submitted for approval');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-white flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-8 py-4 border-b border-gray-200 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-blue-100 flex items-center justify-center">
            <Receipt className="w-5 h-5 text-blue-600" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-gray-900">
              {editBill ? `Edit Bill — ${billNo}` : 'New Bill'}
            </h2>
            <p className="text-xs text-gray-400">Fill in the bill details below</p>
          </div>
        </div>
        <button onClick={onClose} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
          <X className="w-5 h-5" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto">
        <div className="max-w-5xl mx-auto px-8 py-7 space-y-6">

          {/* ── Row 1: Vendor Name  |  Bill# + Order Number ── */}
          <div className="grid grid-cols-2 gap-6">
            {/* Vendor Name */}
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">
                Vendor Name <span className="text-red-500">*</span>
              </label>
              <div className="flex gap-2">
                <div className="flex-1 relative">
                  <select value={form.vendorName} onChange={e => set('vendorName', e.target.value)}
                    className="w-full h-9 pl-3 pr-8 border border-gray-300 rounded-md bg-white text-sm text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 appearance-none">
                    <option value="">Select a vendor</option>
                    {VENDORS.map(v => <option key={v}>{v}</option>)}
                  </select>
                  <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
                <button type="button"
                  className="h-9 px-3 bg-green-600 hover:bg-green-700 text-white rounded-md flex items-center gap-1 text-sm font-medium shrink-0 transition-colors">
                  <Search className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Bill# + Order Number */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">
                  Bill# <span className="text-red-500">*</span>
                </label>
                <Input value={billNo} readOnly
                  className="h-9 text-sm border-gray-300 bg-gray-50 text-gray-600 font-mono cursor-default" />
              </div>
              <div>
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">
                  Order Number
                </label>
                <Input value={form.orderNumber} onChange={e => set('orderNumber', e.target.value)}
                  placeholder="PO / order ref"
                  className="h-9 text-sm border-gray-300 focus:border-blue-500 bg-white" />
              </div>
            </div>
          </div>

          {/* ── Row 2: Bill Date  |  Due Date + Payment Terms ── */}
          <div className="grid grid-cols-2 gap-6">
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">
                Bill Date <span className="text-red-500">*</span>
              </label>
              <Input type="date" value={form.billDate} onChange={e => set('billDate', e.target.value)}
                className="h-9 text-sm border-gray-300 focus:border-blue-500 bg-white" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">Due Date</label>
                <Input type="date" value={form.dueDate} onChange={e => set('dueDate', e.target.value)}
                  className="h-9 text-sm border-gray-300 focus:border-blue-500 bg-white" />
              </div>
              <div>
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">Payment Terms</label>
                <div className="relative">
                  <select value={form.paymentTerms} onChange={e => handlePaymentTermsChange(e.target.value)}
                    className="w-full h-9 pl-3 pr-8 border border-gray-300 rounded-md bg-white text-sm text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 appearance-none">
                    {PAYMENT_TERMS.map(o => <option key={o}>{o}</option>)}
                  </select>
                  <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
              </div>
            </div>
          </div>

          {/* ── Row 3: Accounts Payable  |  Subject ── */}
          <div className="grid grid-cols-2 gap-6">
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 flex items-center gap-1.5">
                Accounts Payable
                <HelpCircle className="w-3.5 h-3.5 text-gray-400" />
              </label>
              <div className="relative">
                <select value={form.accountsPayable} onChange={e => set('accountsPayable', e.target.value)}
                  className="w-full h-9 pl-3 pr-8 border border-gray-300 rounded-md bg-white text-sm text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 appearance-none">
                  <option value="Accounts Payable">Accounts Payable</option>
                  {ACCOUNTS.map(a => <option key={a}>{a}</option>)}
                </select>
                <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
              </div>
            </div>
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 flex items-center justify-between">
                <span>Subject</span>
                <span className="text-gray-400 font-normal normal-case">{250 - form.subject.length} chars left</span>
              </label>
              <Input value={form.subject}
                onChange={e => { if (e.target.value.length <= 250) set('subject', e.target.value); }}
                placeholder="Subject of this bill"
                className="h-9 text-sm border-gray-300 focus:border-blue-500 bg-white" />
            </div>
          </div>

          {/* ── Item Table ── */}
          <div className="border border-gray-200 rounded-2xl overflow-hidden">
            <div className="px-5 pt-4 pb-3 border-b border-gray-100">
              <p className="text-sm font-bold text-gray-800">Item Table</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full" style={{ minWidth: 960 }}>
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-100">
                    <th className="px-3 py-2.5 w-8 text-xs font-semibold text-gray-400 text-center">#</th>
                    <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Item Details</th>
                    <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Account</th>
                    <th className="px-3 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Quantity</th>
                    <th className="px-3 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">
                      Rate <span className="text-blue-500 font-bold">[+]</span>
                    </th>
                    <th className="px-3 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">
                      Discount <span className="text-gray-400 font-normal normal-case">(0%▾)</span>
                    </th>
                    <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Customer Details</th>
                    <th className="px-3 py-2.5 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Amount</th>
                    <th className="px-3 py-2.5 w-8"></th>
                  </tr>
                </thead>
                <tbody>
                  {lineItems.map((row, idx) => (
                    <tr key={row.id} className="group border-b border-gray-100 last:border-0 hover:bg-blue-50/20">
                      <td className="px-3 py-3 text-xs text-gray-400 text-center align-top pt-3.5">{idx + 1}</td>

                      {/* Item Details + sub-links */}
                      <td className="px-3 py-3 align-top" style={{ minWidth: 200 }}>
                        <select value={row.itemName} onChange={e => {
                          const item = ITEMS_CATALOG.find(i => i.name === e.target.value);
                          setCell(row.id, 'itemName', e.target.value);
                          if (item) setCell(row.id, 'rate', item.rate);
                        }}
                          className="w-full h-8 px-2 text-sm border border-gray-200 rounded-md bg-white text-gray-700 focus:outline-none focus:border-blue-400 appearance-none">
                          <option value="">Select item…</option>
                          {ITEMS_CATALOG.map(i => <option key={i.name}>{i.name}</option>)}
                        </select>
                        <div className="flex gap-3 mt-1.5 pl-0.5">
                          <button type="button"
                            className="text-xs text-blue-500 hover:text-blue-700 flex items-center gap-0.5 leading-none">
                            Purchase Discounts <ChevronDown className="w-3 h-3" />
                          </button>
                          <button type="button"
                            className="text-xs text-blue-500 hover:text-blue-700 flex items-center gap-0.5 leading-none">
                            Reporting Tags <ChevronDown className="w-3 h-3" />
                          </button>
                        </div>
                      </td>

                      {/* Account */}
                      <td className="px-3 py-3 align-top" style={{ minWidth: 150 }}>
                        <select value={row.account} onChange={e => setCell(row.id, 'account', e.target.value)}
                          className="w-full h-8 px-2 text-sm border border-gray-200 rounded-md bg-white text-gray-700 focus:outline-none focus:border-blue-400 appearance-none">
                          <option value="">Select…</option>
                          {ACCOUNTS.map(a => <option key={a}>{a}</option>)}
                        </select>
                      </td>

                      {/* Quantity */}
                      <td className="px-3 py-3 align-top" style={{ minWidth: 80 }}>
                        <input type="number" min="0" value={row.quantity}
                          onChange={e => setCell(row.id, 'quantity', parseFloat(e.target.value) || 0)}
                          className="w-full h-8 px-2 text-sm border border-gray-200 rounded-md bg-white text-right focus:outline-none focus:border-blue-400" />
                      </td>

                      {/* Rate */}
                      <td className="px-3 py-3 align-top" style={{ minWidth: 100 }}>
                        <input type="number" min="0" value={row.rate}
                          onChange={e => setCell(row.id, 'rate', parseFloat(e.target.value) || 0)}
                          className="w-full h-8 px-2 text-sm border border-gray-200 rounded-md bg-white text-right focus:outline-none focus:border-blue-400" />
                      </td>

                      {/* Discount % */}
                      <td className="px-3 py-3 align-top" style={{ minWidth: 100 }}>
                        <div className="flex h-8 border border-gray-200 rounded-md overflow-hidden bg-white">
                          <input type="number" min="0" max="100" value={row.discount}
                            onChange={e => setCell(row.id, 'discount', parseFloat(e.target.value) || 0)}
                            className="flex-1 min-w-0 px-2 text-sm text-right focus:outline-none bg-transparent" />
                          <span className="px-2 text-xs text-gray-500 bg-gray-50 border-l border-gray-200 flex items-center shrink-0">%</span>
                        </div>
                      </td>

                      {/* Customer Details */}
                      <td className="px-3 py-3 align-top" style={{ minWidth: 150 }}>
                        <input type="text" value={row.customerDetails}
                          onChange={e => setCell(row.id, 'customerDetails', e.target.value)}
                          placeholder="Customer…"
                          className="w-full h-8 px-2 text-sm border border-gray-200 rounded-md bg-white focus:outline-none focus:border-blue-400" />
                      </td>

                      {/* Amount */}
                      <td className="px-3 py-3 text-right align-top pt-3.5" style={{ minWidth: 110 }}>
                        <span className="text-sm font-semibold text-gray-800">
                          {formatINR(row.quantity * row.rate * (1 - row.discount / 100))}
                        </span>
                      </td>

                      {/* Delete */}
                      <td className="px-3 py-3 text-center align-top pt-3">
                        <button type="button" onClick={() => removeRow(row.id)}
                          className="text-gray-300 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-all">
                          <X className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Add Row — split button */}
            <div className="px-5 py-3 border-t border-gray-100 flex items-center gap-4">
              <div className="flex rounded-md overflow-hidden border border-gray-200 text-sm">
                <button type="button" onClick={addRow}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-blue-600 hover:bg-blue-50 font-medium transition-colors">
                  <Plus className="w-3.5 h-3.5" /> Add New Row
                </button>
                <button type="button"
                  className="px-2 py-1.5 text-blue-600 hover:bg-blue-50 border-l border-gray-200 transition-colors">
                  <ChevronDown className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>

          {/* ── Notes / Attach / Additional  +  Totals ── */}
          <div className="flex gap-8 items-start">

            {/* Left column */}
            <div className="flex-1 space-y-5">
              {/* Notes */}
              <div>
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5 block">Notes</label>
                <textarea value={form.notes} onChange={e => set('notes', e.target.value)}
                  rows={3} placeholder="Add any notes…"
                  className="w-full resize-none px-3 py-2 text-sm border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 placeholder-gray-400" />
                <p className="text-xs text-gray-400 mt-1 italic">It will not be shown in PDF</p>
              </div>

              {/* Attach Files */}
              <div>
                <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2 block">
                  Attach File(s) to Bill
                </label>
                <div className="border-2 border-dashed border-gray-200 rounded-xl p-5 flex flex-col items-center gap-2.5 hover:border-blue-300 transition-colors cursor-pointer bg-gray-50/50">
                  <Paperclip className="w-5 h-5 text-gray-400" />
                  <div className="flex rounded-md overflow-hidden border border-gray-200 text-xs">
                    <button type="button"
                      className="flex items-center gap-1 px-3 py-1.5 text-blue-600 hover:bg-blue-50 font-medium bg-white transition-colors">
                      <Plus className="w-3 h-3" /> Upload File
                    </button>
                    <button type="button"
                      className="px-2 py-1.5 text-blue-600 hover:bg-blue-50 border-l border-gray-200 bg-white transition-colors">
                      <ChevronDown className="w-3 h-3" />
                    </button>
                  </div>
                  <p className="text-xs text-gray-400">Or drop files here · Max 5 files, 10 MB each</p>
                </div>
              </div>

              {/* Additional Fields */}
              <div className="flex items-center gap-2.5 p-3.5 bg-gray-50 rounded-xl border border-gray-100">
                <Settings className="w-4 h-4 text-gray-400 shrink-0" />
                <p className="text-xs text-gray-500 leading-relaxed">
                  You can add custom fields from{' '}
                  <button type="button" className="text-blue-600 hover:underline font-medium">
                    Settings → Purchases → Bills
                  </button>
                </p>
              </div>
            </div>

            {/* Right column — Totals */}
            <div className="w-72 shrink-0">
              <div className="bg-gray-50 rounded-2xl border border-gray-200 overflow-visible">

                {/* Sub Total */}
                <div className="px-5 py-3.5 flex justify-between border-b border-gray-100">
                  <span className="text-sm text-gray-600">Sub Total</span>
                  <span className="text-sm font-semibold text-gray-800">{formatINR(subTotal)}</span>
                </div>

                {/* TDS / TCS */}
                <div className="px-5 py-3.5 border-b border-gray-100 space-y-2">
                  <div className="flex items-center gap-5">
                    <label className="flex items-center gap-1.5 text-sm text-gray-700 cursor-pointer select-none">
                      <input type="radio" name="tdsOrTcs" value="tds"
                        checked={form.tdsOrTcs === 'tds'} onChange={() => set('tdsOrTcs', 'tds')}
                        className="accent-blue-600" />
                      TDS
                    </label>
                    <label className="flex items-center gap-1.5 text-sm text-gray-700 cursor-pointer select-none">
                      <input type="radio" name="tdsOrTcs" value="tcs"
                        checked={form.tdsOrTcs === 'tcs'} onChange={() => set('tdsOrTcs', 'tcs')}
                        className="accent-blue-600" />
                      TCS
                    </label>
                  </div>
                  <div className="relative">
                    <select value={form.selectedTax} onChange={e => set('selectedTax', e.target.value)}
                      className="w-full h-8 pl-3 pr-8 border border-gray-200 rounded-md bg-white text-sm text-gray-700 focus:outline-none focus:border-blue-400 appearance-none">
                      <option value="">Select a Tax</option>
                      {TAX_RATES.filter(t => t !== 'None').map(t => <option key={t}>{t}</option>)}
                    </select>
                    <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400 pointer-events-none" />
                  </div>
                </div>

                {/* Adjustment */}
                <div className="px-5 py-3.5 flex items-center justify-between gap-2 border-b border-gray-100">
                  <div className="flex items-center gap-1.5 shrink-0">
                    <span className="text-sm text-gray-600 border-b border-dashed border-gray-400 leading-tight cursor-help">
                      Adjustment
                    </span>
                    <HelpCircle className="w-3.5 h-3.5 text-gray-400" />
                  </div>
                  <input type="number" value={form.adjustment}
                    onChange={e => set('adjustment', e.target.value)}
                    className="w-24 h-8 px-2 text-sm border border-gray-200 rounded-md bg-white text-right focus:outline-none focus:border-blue-400" />
                </div>

                {/* Total */}
                <div className="px-5 py-4 flex justify-between bg-white rounded-b-2xl">
                  <span className="text-base font-bold text-gray-900">Total</span>
                  <span className="text-base font-bold text-blue-600">{formatINR(total)}</span>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>

      {/* ── Footer ── */}
      <div className="px-8 py-4 border-t border-gray-200 flex items-center justify-between shrink-0 bg-white">
        {/* Left: action buttons */}
        <div className="flex items-center gap-3">
          <Button variant="outline" onClick={() => handleSave('draft')}
            className="h-9 px-5 text-sm border-gray-300 text-gray-700 hover:bg-gray-50 font-semibold">
            Save as Draft
          </Button>
          <Button onClick={() => handleSave('pending_approval')}
            className="h-9 px-5 text-sm bg-green-600 hover:bg-green-700 text-white font-semibold">
            Save as Open
          </Button>
          <Button variant="ghost" onClick={onClose}
            className="h-9 px-4 text-sm text-gray-500 hover:text-gray-700">
            Cancel
          </Button>
        </div>

        {/* Right: PDF template + Make Recurring */}
        <div className="flex items-center gap-5 text-xs text-gray-500">
          <span>
            PDF Template:{' '}
            <span className="font-semibold text-gray-700">'Standard Template'</span>{' '}
            <button type="button" className="text-blue-600 hover:underline font-medium ml-1">Change</button>
          </span>
          <button type="button"
            className="flex items-center gap-1.5 text-blue-600 hover:underline font-medium">
            <RefreshCw className="w-3.5 h-3.5" /> Make Recurring
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Row Kebab ────────────────────────────────────────────
function RowMenu({ bill, onView, onEdit, onApprove, onDelete }: {
  bill: Bill; onView: () => void; onEdit: () => void;
  onApprove: () => void; onDelete: () => void;
}) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useOutsideClick(ref, () => setOpen(false));
  return (
    <div ref={ref} className="relative">
      <button type="button" onClick={() => setOpen(o => !o)}
        className="p-1.5 rounded-md text-gray-400 hover:text-gray-600 hover:bg-gray-100 opacity-0 group-hover:opacity-100 transition-all">
        <MoreVertical className="w-4 h-4" />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1 bg-white border border-gray-200 rounded-xl shadow-lg py-1 w-40 z-50">
          <button type="button" onClick={() => { onView(); setOpen(false); }}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-700">
            <Eye className="w-3.5 h-3.5" /> View Bill
          </button>
          {(bill.status === 'draft' || bill.status === 'pending_approval') && (
            <button type="button" onClick={() => { onEdit(); setOpen(false); }}
              className="w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-700">
              <Edit2 className="w-3.5 h-3.5" /> Edit
            </button>
          )}
          {bill.status === 'pending_approval' && (
            <button type="button" onClick={() => { onApprove(); setOpen(false); }}
              className="w-full flex items-center gap-2 px-3 py-2 text-sm text-green-700 hover:bg-green-50">
              <CheckCircle2 className="w-3.5 h-3.5" /> Approve
            </button>
          )}
          <div className="border-t border-gray-100 my-1" />
          <button type="button" onClick={() => { onDelete(); setOpen(false); }}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-red-500 hover:bg-red-50">
            <Trash2 className="w-3.5 h-3.5" /> Delete
          </button>
        </div>
      )}
    </div>
  );
}

// ─── View options (Zoho-style) ────────────────────────────
type ViewKey = 'All' | 'Draft' | 'Pending Approval' | 'Open' | 'Overdue' | 'Unpaid' | 'Partially Paid' | 'Paid' | 'Void';

const VIEW_FILTER: Record<ViewKey, (b: Bill) => boolean> = {
  'All':              ()  => true,
  'Draft':            b  => b.status === 'draft',
  'Pending Approval': b  => b.status === 'pending_approval',
  'Open':             b  => b.status === 'approved',
  'Overdue':          b  => b.status === 'overdue',
  'Unpaid':           b  => b.status === 'approved' || b.status === 'overdue',
  'Partially Paid':   ()  => false,   // placeholder — no partial-pay status yet
  'Paid':             b  => b.status === 'paid',
  'Void':             b  => b.status === 'rejected',
};

const VIEW_LABELS: ViewKey[] = [
  'All', 'Draft', 'Pending Approval', 'Open',
  'Overdue', 'Unpaid', 'Partially Paid', 'Paid', 'Void',
];

// ─── Main Page ─────────────────────────────────────────────
export default function PurchaseBillsPage() {
  const [bills, setBills] = useState<Bill[]>(DEMO_BILLS);
  const [showAutoGen, setShowAutoGen] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [viewBill, setViewBill] = useState<Bill | null>(null);
  const [editBill, setEditBill] = useState<Bill | null>(null);

  // Zoho-style view filter (replaces the tab bar)
  const [currentView, setCurrentView] = useState<ViewKey>('Unpaid');
  const [viewDropOpen, setViewDropOpen] = useState(false);
  const [viewSearch, setViewSearch] = useState('');
  const viewDropRef = useRef<HTMLDivElement>(null);
  useOutsideClick(viewDropRef, () => { setViewDropOpen(false); setViewSearch(''); });

  // Table state
  const [search, setSearch] = useState('');
  const [viewMode, setViewMode] = useState<'list' | 'calendar'>('list');
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());

  const filtered = bills.filter(b => {
    const matchView   = VIEW_FILTER[currentView](b);
    const matchSearch = b.billNumber.toLowerCase().includes(search.toLowerCase()) ||
                        b.vendorName.toLowerCase().includes(search.toLowerCase()) ||
                        b.poReference.toLowerCase().includes(search.toLowerCase());
    return matchView && matchSearch;
  });

  // Auto-generate bill from a real StoredPO (with actual line items)
  const handleAutoGenerate = (po: StoredPO) => {
    const today = new Date().toISOString().split('T')[0];

    // Build bill line items from the PO's stored items
    const lineItems: BillLineItem[] = po.items
      .filter(i => i.itemName)
      .map((item, idx) => ({
        id:              idx + 1,
        itemName:        item.itemName,
        account:         item.account,
        quantity:        item.quantity,
        rate:            item.rate,
        tax:             item.tax || 'GST 5%',
        discount:        item.discount ?? 0,
        customerDetails: item.customerDetails ?? '',
      }));

    // Recompute accurate totals from the items
    const subTotal = lineItems.reduce((s, i) => s + i.quantity * i.rate * (1 - i.discount / 100), 0);
    const taxAmt   = lineItems.reduce((s, i) => {
      const pct = i.tax === 'GST 5%' ? 0.05 : i.tax === 'GST 12%' ? 0.12 : i.tax === 'GST 18%' ? 0.18 : i.tax === 'GST 28%' ? 0.28 : 0;
      return s + (i.quantity * i.rate * (1 - i.discount / 100) * pct);
    }, 0);
    const total = subTotal + taxAmt;

    const newBill: Bill = {
      id:            Date.now(),
      billNumber:    genBillNumber(),
      vendorName:    po.vendorName,
      poReference:   po.poNumber,
      billDate:      today,
      dueDate:       addDays(today, 30),
      paymentTerms:  po.paymentTerms || 'Net 30',
      status:        'pending_approval',
      autoGenerated: true,
      lineItems,
      notes:              `Auto-generated from ${po.poNumber}`,
      termsAndConditions: 'Payment within 30 days.',
      approvedBy: '', approvedAt: '', rejectedReason: '',
      subTotal, discount: 0, tax: taxAmt, total,
    };

    // Mark the source PO as billed in the shared store (lifecycle update)
    markPOBilled(po.poNumber);

    setBills(p => [newBill, ...p]);
    setViewBill(newBill);
    toast.success(`Bill auto-generated from ${po.poNumber} — ready for review`);
  };

  const handleSaveBill = (bill: Bill) => {
    setBills(prev => {
      const exists = prev.find(b => b.id === bill.id);
      return exists ? prev.map(b => b.id === bill.id ? bill : b) : [bill, ...prev];
    });
  };

  const handleApprove = (id: number) => {
    setBills(p => p.map(b => b.id === id
      ? { ...b, status: 'approved', approvedBy: 'Admin', approvedAt: new Date().toISOString() }
      : b));
    toast.success('Bill approved successfully');
  };

  const handleReject = (id: number) => {
    setBills(p => p.map(b => b.id === id ? { ...b, status: 'rejected' } : b));
  };

  const handleDelete = (id: number) => {
    setBills(p => p.filter(b => b.id !== id));
    toast.success('Bill deleted');
  };

  const openEdit = (bill: Bill) => { setEditBill(bill); setShowForm(true); };

  const counts = {
    all:              bills.length,
    draft:            bills.filter(b => b.status === 'draft').length,
    pending_approval: bills.filter(b => b.status === 'pending_approval').length,
    approved:         bills.filter(b => b.status === 'approved').length,
    paid:             bills.filter(b => b.status === 'paid').length,
    overdue:          bills.filter(b => b.status === 'overdue').length,
    rejected:         bills.filter(b => b.status === 'rejected').length,
  };

  const totalPending  = bills.filter(b => b.status === 'pending_approval').reduce((s, b) => s + b.total, 0);
  const totalApproved = bills.filter(b => b.status === 'approved').reduce((s, b) => s + b.total, 0);
  const totalOverdue  = bills.filter(b => b.status === 'overdue').reduce((s, b) => s + b.total, 0);

  // checkbox helpers
  const allSelected = filtered.length > 0 && filtered.every(b => selectedIds.has(b.id));
  const toggleAll   = () => setSelectedIds(allSelected ? new Set() : new Set(filtered.map(b => b.id)));
  const toggleOne   = (id: number) => setSelectedIds(prev => {
    const s = new Set(prev);
    s.has(id) ? s.delete(id) : s.add(id);
    return s;
  });

  const balanceDue = (b: Bill) => (b.status === 'paid' ? 0 : b.total);

  const filteredViews = VIEW_LABELS.filter(v =>
    v.toLowerCase().includes(viewSearch.toLowerCase())
  );

  return (
    <div className="flex flex-col h-full bg-white">
      {/* ── Modals ── */}
      {showAutoGen && (
        <AutoGenerateModal
          onClose={() => setShowAutoGen(false)}
          onGenerate={(po) => handleAutoGenerate(po)}
        />
      )}
      {showForm && (
        <BillForm
          onClose={() => { setShowForm(false); setEditBill(null); }}
          onSave={handleSaveBill}
          editBill={editBill}
        />
      )}
      {viewBill && (
        <BillViewModal
          bill={viewBill}
          onClose={() => setViewBill(null)}
          onApprove={handleApprove}
          onReject={handleReject}
          onEdit={bill => { setViewBill(null); openEdit(bill); }}
        />
      )}

      {/* ── Top bar (Zoho-style) ── */}
      <div className="flex items-center justify-between px-6 py-3 border-b border-gray-200 bg-white shrink-0">

        {/* Left: view-title dropdown */}
        <div ref={viewDropRef} className="relative">
          <button
            type="button"
            onClick={() => { setViewDropOpen(o => !o); setViewSearch(''); }}
            className="flex items-center gap-1.5 text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors group">
            {currentView === 'Unpaid' ? 'Unpaid Bills' : `${currentView} Bills`}
            <ChevronDown className={`w-5 h-5 text-gray-400 group-hover:text-blue-500 transition-transform ${viewDropOpen ? 'rotate-180' : ''}`} />
          </button>

          {/* View dropdown */}
          {viewDropOpen && (
            <div className="absolute left-0 top-full mt-1 bg-white border border-gray-200 rounded-xl shadow-xl w-72 z-50 overflow-hidden">
              {/* Search */}
              <div className="px-3 py-2.5 border-b border-gray-100">
                <div className="relative">
                  <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
                  <input
                    autoFocus
                    value={viewSearch}
                    onChange={e => setViewSearch(e.target.value)}
                    placeholder="Search views…"
                    className="w-full h-8 pl-8 pr-3 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-blue-400 bg-white"
                  />
                </div>
              </div>
              {/* Options */}
              <div className="py-1 max-h-72 overflow-y-auto">
                {filteredViews.map(v => (
                  <button key={v} type="button"
                    onClick={() => { setCurrentView(v); setViewDropOpen(false); setViewSearch(''); }}
                    className={`w-full flex items-center justify-between px-4 py-2.5 text-sm transition-colors ${
                      currentView === v ? 'bg-blue-50 text-blue-700 font-semibold' : 'text-gray-700 hover:bg-gray-50'
                    }`}>
                    <span>{v}</span>
                    <svg className="w-4 h-4 text-gray-300 hover:text-amber-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
                    </svg>
                  </button>
                ))}
                {filteredViews.length === 0 && (
                  <p className="px-4 py-3 text-sm text-gray-400">No views found</p>
                )}
              </div>
              {/* New custom view */}
              <div className="border-t border-gray-100 px-4 py-2.5">
                <button type="button"
                  className="flex items-center gap-2 text-sm text-blue-600 hover:text-blue-700 font-medium">
                  <div className="w-4 h-4 rounded-full bg-blue-600 flex items-center justify-center">
                    <Plus className="w-2.5 h-2.5 text-white" />
                  </div>
                  New Custom View
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Right: view-mode + New split + more */}
        <div className="flex items-center gap-2">
          {/* List / Calendar toggle */}
          <div className="flex items-center border border-gray-200 rounded-lg overflow-hidden">
            <button type="button"
              onClick={() => setViewMode('list')}
              title="List view"
              className={`px-2.5 py-2 transition-colors ${viewMode === 'list' ? 'bg-gray-100 text-gray-700' : 'text-gray-400 hover:bg-gray-50'}`}>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 10h16M4 14h16M4 18h16" />
              </svg>
            </button>
            <button type="button"
              onClick={() => setViewMode('calendar')}
              title="Calendar view"
              className={`px-2.5 py-2 border-l border-gray-200 transition-colors ${viewMode === 'calendar' ? 'bg-gray-100 text-gray-700' : 'text-gray-400 hover:bg-gray-50'}`}>
              <Calendar className="w-4 h-4" />
            </button>
          </div>

          {/* Auto-generate (kept as icon button) */}
          <button type="button"
            onClick={() => setShowAutoGen(true)}
            title="Auto-Generate from PO"
            className="h-9 px-3 border border-blue-200 text-blue-600 hover:bg-blue-50 rounded-lg flex items-center gap-1.5 text-xs font-semibold transition-colors">
            <Zap className="w-3.5 h-3.5" /> Auto-Generate
          </button>

          {/* + New split button (green) */}
          <div className="flex rounded-lg overflow-hidden shadow-sm">
            <button type="button"
              onClick={() => { setEditBill(null); setShowForm(true); }}
              className="flex items-center gap-1.5 px-4 py-2 bg-green-500 hover:bg-green-600 text-white text-sm font-semibold transition-colors">
              <Plus className="w-4 h-4" /> New
            </button>
            <button type="button"
              className="px-2 py-2 bg-green-500 hover:bg-green-600 text-white border-l border-green-400 transition-colors">
              <ChevronDown className="w-4 h-4" />
            </button>
          </div>

          {/* More options */}
          <button type="button"
            className="h-9 w-9 flex items-center justify-center border border-gray-200 rounded-lg text-gray-500 hover:bg-gray-50 transition-colors">
            <MoreVertical className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* ── Table area ── */}
      <div className="flex-1 overflow-auto bg-white">
        {viewMode === 'calendar' ? (
          /* ── Calendar placeholder ── */
          <div className="flex flex-col items-center justify-center h-full text-gray-400 gap-3">
            <Calendar className="w-12 h-12 text-gray-200" />
            <p className="text-sm font-medium">Calendar view coming soon</p>
            <button type="button" onClick={() => setViewMode('list')}
              className="text-xs text-blue-600 hover:underline">Switch to List view</button>
          </div>
        ) : (
          <table className="w-full">
            <thead className="sticky top-0 z-10">
              <tr className="bg-gray-50 border-b border-gray-200">
                {/* Settings + checkbox col */}
                <th className="w-10 px-3 py-3 border-r border-gray-100">
                  <div className="flex items-center gap-1">
                    <button type="button" title="Column settings"
                      className="text-gray-400 hover:text-gray-600">
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
                      </svg>
                    </button>
                  </div>
                </th>
                <th className="w-8 px-3 py-3">
                  <input type="checkbox" checked={allSelected} onChange={toggleAll}
                    className="w-3.5 h-3.5 accent-blue-600 cursor-pointer" />
                </th>
                {[
                  { label: 'Date',             cls: '' },
                  { label: 'Bill #',           cls: '' },
                  { label: 'Reference Number', cls: '' },
                  { label: 'Vendor Name',      cls: '' },
                  { label: 'Status',           cls: '' },
                  { label: 'Due Date',         cls: '' },
                  { label: 'Amount',           cls: 'text-right' },
                  { label: 'Balance Due',      cls: 'text-right' },
                  { label: '',                 cls: 'w-10' },
                ].map(h => (
                  <th key={h.label}
                    className={`px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide whitespace-nowrap ${h.cls}`}>
                    {h.label}
                  </th>
                ))}
              </tr>
              {/* Search bar row */}
              <tr className="bg-white border-b border-gray-100">
                <td colSpan={11} className="px-4 py-2">
                  <div className="relative max-w-sm">
                    <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
                    <input value={search} onChange={e => setSearch(e.target.value)}
                      placeholder={`Search ${currentView === 'Unpaid' ? 'Unpaid Bills' : currentView + ' Bills'}…`}
                      className="w-full h-7 pl-8 pr-3 text-xs border border-gray-200 rounded-md bg-white focus:outline-none focus:ring-1 focus:ring-blue-400 focus:border-blue-400" />
                    {search && (
                      <button onClick={() => setSearch('')}
                        className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                        <X className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            </thead>

            <tbody className="divide-y divide-gray-100">
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={11} className="px-4 py-20 text-center">
                    <div className="flex flex-col items-center gap-3">
                      <Receipt className="w-10 h-10 text-gray-200" />
                      <p className="text-sm text-gray-400 font-medium">
                        There are no {currentView === 'Unpaid' ? 'Unpaid' : currentView} Bills
                      </p>
                      <div className="flex gap-2 mt-1">
                        <Button onClick={() => setShowAutoGen(true)} size="sm" variant="outline"
                          className="h-8 px-3 text-xs border-blue-200 text-blue-600 font-semibold gap-1">
                          <Zap className="w-3.5 h-3.5" /> Auto-Generate
                        </Button>
                        <Button onClick={() => { setEditBill(null); setShowForm(true); }} size="sm"
                          className="h-8 px-3 text-xs bg-green-500 hover:bg-green-600 text-white font-semibold gap-1">
                          <Plus className="w-3.5 h-3.5" /> New Bill
                        </Button>
                      </div>
                    </div>
                  </td>
                </tr>
              ) : filtered.map(b => (
                <tr key={b.id}
                  className={`group transition-colors cursor-pointer ${
                    selectedIds.has(b.id) ? 'bg-blue-50/60' : 'hover:bg-gray-50'
                  }`}
                  onClick={() => setViewBill(b)}>

                  {/* Empty settings col */}
                  <td className="w-10 px-3 py-3 border-r border-gray-100" onClick={e => e.stopPropagation()} />

                  {/* Checkbox */}
                  <td className="w-8 px-3 py-3" onClick={e => e.stopPropagation()}>
                    <input type="checkbox"
                      checked={selectedIds.has(b.id)}
                      onChange={() => toggleOne(b.id)}
                      className="w-3.5 h-3.5 accent-blue-600 cursor-pointer" />
                  </td>

                  {/* Date */}
                  <td className="px-4 py-3 text-sm text-gray-600 whitespace-nowrap">
                    {formatDate(b.billDate)}
                  </td>

                  {/* Bill # */}
                  <td className="px-4 py-3" onClick={e => e.stopPropagation()}>
                    <button type="button" onClick={() => setViewBill(b)}
                      className="text-sm font-semibold text-blue-600 hover:text-blue-700 hover:underline whitespace-nowrap">
                      {b.billNumber}
                    </button>
                  </td>

                  {/* Reference Number */}
                  <td className="px-4 py-3">
                    {b.poReference
                      ? <span className="text-xs font-mono text-gray-600 bg-gray-100 px-1.5 py-0.5 rounded">
                          {b.poReference}
                        </span>
                      : <span className="text-sm text-gray-300">—</span>
                    }
                  </td>

                  {/* Vendor Name */}
                  <td className="px-4 py-3 text-sm text-gray-800 font-medium">{b.vendorName}</td>

                  {/* Status */}
                  <td className="px-4 py-3">
                    <StatusBadge status={b.status} />
                  </td>

                  {/* Due Date */}
                  <td className="px-4 py-3 whitespace-nowrap">
                    <span className={`text-sm ${b.status === 'overdue' ? 'text-red-600 font-semibold' : 'text-gray-600'}`}>
                      {formatDate(b.dueDate)}
                    </span>
                  </td>

                  {/* Amount */}
                  <td className="px-4 py-3 text-sm font-semibold text-gray-800 text-right whitespace-nowrap">
                    {formatINR(b.total)}
                  </td>

                  {/* Balance Due */}
                  <td className="px-4 py-3 text-sm font-semibold text-right whitespace-nowrap">
                    {balanceDue(b) === 0
                      ? <span className="text-gray-400">{formatINR(0)}</span>
                      : <span className={b.status === 'overdue' ? 'text-red-600' : 'text-gray-800'}>
                          {formatINR(balanceDue(b))}
                        </span>
                    }
                  </td>

                  {/* Actions */}
                  <td className="px-3 py-3 w-10" onClick={e => e.stopPropagation()}>
                    <div className="flex items-center gap-1 justify-end">
                      {b.status === 'pending_approval' && (
                        <button type="button" onClick={() => setViewBill(b)}
                          className="opacity-0 group-hover:opacity-100 flex items-center gap-1 px-2 py-1 bg-amber-500 hover:bg-amber-600 text-white text-xs font-semibold rounded transition-all">
                          <Eye className="w-3 h-3" /> Review
                        </button>
                      )}
                      <RowMenu bill={b}
                        onView={() => setViewBill(b)}
                        onEdit={() => openEdit(b)}
                        onApprove={() => handleApprove(b.id)}
                        onDelete={() => handleDelete(b.id)}
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
